project:
  type: website

website:
  title: "gauge-block-study"
  navbar:
    left:
      - href: index.qmd
        text: EN
      - href: RO.qmd
        text: RO
      - gaugefinder.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual