<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vlad Marianciuc">
<meta name="author" content="Îndrumător: Conf.dr. Iulian Cîmpean">
<meta name="dcterms.date" content="2024-06-16">

<title>gauge-block-study - Arta preciziei: o explorare matematică a unui set de cale plan paralele</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">gauge-block-study</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">EN</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./RO.html" rel="" target="" aria-current="page">
 <span class="menu-text">RO</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./gaugefinder.html" rel="" target="">
 <span class="menu-text">GaugeBlock Finder</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Cuprins</h2>
   
  <ul>
  <li><a href="#introducere" id="toc-introducere" class="nav-link active" data-scroll-target="#introducere">1. Introducere</a>
  <ul class="collapse">
  <li><a href="#1.1" id="toc-1.1" class="nav-link" data-scroll-target="#1.1">1.1 Alegerea temei</a></li>
  <li><a href="#natura-temei-alese" id="toc-natura-temei-alese" class="nav-link" data-scroll-target="#natura-temei-alese">1.2 Natura temei alese</a></li>
  <li><a href="#prezentarea-generală-a-temei" id="toc-prezentarea-generală-a-temei" class="nav-link" data-scroll-target="#prezentarea-generală-a-temei">1.3 Prezentarea generală a temei</a>
  <ul class="collapse">
  <li><a href="#definirea-datelor-problemei" id="toc-definirea-datelor-problemei" class="nav-link" data-scroll-target="#definirea-datelor-problemei">1.3.1 Definirea datelor problemei</a></li>
  <li><a href="#enunțarea-problemei" id="toc-enunțarea-problemei" class="nav-link" data-scroll-target="#enunțarea-problemei">1.3.2 Enunțarea problemei</a></li>
  <li><a href="#1.3.3" id="toc-1.3.3" class="nav-link" data-scroll-target="#1.3.3">1.3.3 Intuiție inițială</a></li>
  <li><a href="#considerente-pragmatice" id="toc-considerente-pragmatice" class="nav-link" data-scroll-target="#considerente-pragmatice">1.3.4 Considerente pragmatice</a></li>
  <li><a href="#considerente-istorice" id="toc-considerente-istorice" class="nav-link" data-scroll-target="#considerente-istorice">1.3.5 Considerente istorice</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#problema-de-numărare" id="toc-problema-de-numărare" class="nav-link" data-scroll-target="#problema-de-numărare">2. Problema de numărare</a>
  <ul class="collapse">
  <li><a href="#abordarea-naivă" id="toc-abordarea-naivă" class="nav-link" data-scroll-target="#abordarea-naivă">2.1 Abordarea naivă</a></li>
  <li><a href="#formulare-matematică" id="toc-formulare-matematică" class="nav-link" data-scroll-target="#formulare-matematică">2.2 Formulare matematică</a></li>
  <li><a href="#reducere" id="toc-reducere" class="nav-link" data-scroll-target="#reducere">2.3 Reducere</a></li>
  <li><a href="#ajustarea-intuiției-inițiale" id="toc-ajustarea-intuiției-inițiale" class="nav-link" data-scroll-target="#ajustarea-intuiției-inițiale">2.4 Ajustarea intuiției inițiale</a></li>
  <li><a href="#reformulare-și-rezolvare" id="toc-reformulare-și-rezolvare" class="nav-link" data-scroll-target="#reformulare-și-rezolvare">2.5 Reformulare și rezolvare</a></li>
  <li><a href="#capete" id="toc-capete" class="nav-link" data-scroll-target="#capete">2.6 Capete</a></li>
  <li><a href="#concluzii" id="toc-concluzii" class="nav-link" data-scroll-target="#concluzii">2.7 Concluzii</a></li>
  </ul></li>
  <li><a href="#optimizare-și-algoritm" id="toc-optimizare-și-algoritm" class="nav-link" data-scroll-target="#optimizare-și-algoritm">3. Optimizare și algoritm</a>
  <ul class="collapse">
  <li><a href="#optimizare" id="toc-optimizare" class="nav-link" data-scroll-target="#optimizare">3.1 Optimizare</a></li>
  <li><a href="#algoritm" id="toc-algoritm" class="nav-link" data-scroll-target="#algoritm">3.2 Algoritm</a></li>
  </ul></li>
  <li><a href="#incertitudinea-unei-măsurători" id="toc-incertitudinea-unei-măsurători" class="nav-link" data-scroll-target="#incertitudinea-unei-măsurători">4. Incertitudinea unei măsurători</a>
  <ul class="collapse">
  <li><a href="#cale-plan-paralele-caracteristici-metrologice" id="toc-cale-plan-paralele-caracteristici-metrologice" class="nav-link" data-scroll-target="#cale-plan-paralele-caracteristici-metrologice">4.1 Cale plan paralele – caracteristici metrologice</a>
  <ul class="collapse">
  <li><a href="#condiții-standard-de-referință" id="toc-condiții-standard-de-referință" class="nav-link" data-scroll-target="#condiții-standard-de-referință">4.1.1 Condiții standard de referință</a></li>
  <li><a href="#stratul-de-calare" id="toc-stratul-de-calare" class="nav-link" data-scroll-target="#stratul-de-calare">4.1.2 Stratul de calare</a></li>
  <li><a href="#grade-de-toleranță" id="toc-grade-de-toleranță" class="nav-link" data-scroll-target="#grade-de-toleranță">4.1.3 Grade de toleranță</a></li>
  </ul></li>
  <li><a href="#remarcă-privind-numărul-de-cale-calate" id="toc-remarcă-privind-numărul-de-cale-calate" class="nav-link" data-scroll-target="#remarcă-privind-numărul-de-cale-calate">4.2 Remarcă privind numărul de cale calate</a>
  <ul class="collapse">
  <li><a href="#modelarea-incertitudinii" id="toc-modelarea-incertitudinii" class="nav-link" data-scroll-target="#modelarea-incertitudinii">4.2.1 Modelarea incertitudinii</a></li>
  <li><a href="#formulare-matematică-algoritm" id="toc-formulare-matematică-algoritm" class="nav-link" data-scroll-target="#formulare-matematică-algoritm">4.2.2 Formulare matematică + algoritm</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#mulțumesc" id="toc-mulțumesc" class="nav-link" data-scroll-target="#mulțumesc">5. Mulțumesc:</a></li>
  <li><a href="#bibliografie" id="toc-bibliografie" class="nav-link" data-scroll-target="#bibliografie">6. Bibliografie</a></li>
  <li><a href="#imagini" id="toc-imagini" class="nav-link" data-scroll-target="#imagini">7. Imagini</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Arta preciziei: o explorare matematică a unui set de cale plan paralele</h1>
<p class="subtitle lead">Lucrare de licență - Facultatea de Matematică și Informatică, Universitatea București</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Vlad Marianciuc </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Bucharest
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://sites.google.com/site/iulianncimpean/home">Îndrumător: Conf.dr. Iulian Cîmpean</a> </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Bucharest
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstract</div>
    O incursiune matematică în fascinanta lume a preciziei și metrologiei. Pornind de la aspectele combinatorice ale unui set de cale plan paralele, această lucrare studiază intervalul de măsuri realizabile, numărul lor și criteriile obținerii unei combinații optime. Subliniază importanța selectării clasei de precizie adecvate pentru a asigura acuratețea optimă a măsurătorilor și aduce în discuție echilibrul complicat de planeitate, paralelism și exactitate pe care o cale plan paralela trebuie să-l îndeplinească. Pe lângă eleganța și simplitatea matematică a acestor instrumente, lucrarea evidențiază rolul critic pe care acestea îl au (și l-au avut) în menținerea avansării tehnologiei.
  </div>
</div>

</header>

<section id="introducere" class="level1">
<h1>1. Introducere</h1>
<section id="1.1" class="level2">
<h2 class="anchored" data-anchor-id="1.1">1.1 Alegerea temei</h2>
<p>Tema lucrării a fost aleasă în urma vizionării videoclipului „Origins of precision”<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> al utilizatorului Machine Thinking de pe platforma YouTube. Videoclipul respectiv prezintă sumar dezvoltarea si creșterea preciziei de măsurare de-a lungul istoriei. El se termină cu o problemă deschisă generată de câteva afirmații care sunt prezente pe foaia de prezentare al unui set de cale plan paralele Ford-Johansson.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://youtu.be/gNRnrn5DE58?feature=shared&amp;t=1018"><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2001.png" class="img-fluid figure-img"></a></p>
<figcaption class="figure-caption">Fig.1 Foaia de prezentare al unui set cu 81 de cale plan paralele din 1944</figcaption>
</figure>
</div>
<p>Mai exact, este vorba despre 2 afirmații făcute aici:</p>
<ul>
<li><p>a) „ Folosind piesele acestui set, se pot obține măsuri între 0.1″ și 0.2″ cu pas de 0.001″ și între 0.2″ și 10″ cu pas de 0.0001″ ” (traducere personală din Fig 2.)</p></li>
<li><p>b) „ Mai mult de 100 000 de combinații sunt posibile folosind acest set cu 81 de piese ” (traducere personală din Fig 2.)</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2002.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.2 Afirmațiile de la care a pornit lucrarea (zoom Fig.1)</figcaption>
</figure>
</div>
</section>
<section id="natura-temei-alese" class="level2">
<h2 class="anchored" data-anchor-id="natura-temei-alese">1.2 Natura temei alese</h2>
<p>Topicurile discutate în lucrarea de față se încadrează în 2 domenii matematice:</p>
<ul>
<li><p>a) Combinatorică: Probleme de numărare și optimizare</p></li>
<li><p>b) Statistică: Evaluarea incertitudinii de măsurare</p></li>
</ul>
<p>Pe lângă aceste 2 domenii, lucrarea conține comentarii și precizări de natură istorică și practică.</p>
</section>
<section id="prezentarea-generală-a-temei" class="level2">
<h2 class="anchored" data-anchor-id="prezentarea-generală-a-temei">1.3 Prezentarea generală a temei</h2>
<section id="definirea-datelor-problemei" class="level3">
<h3 class="anchored" data-anchor-id="definirea-datelor-problemei">1.3.1 Definirea datelor problemei</h3>
<p><br></p>
<ul>
<li><p><u>a) Calele plan paralele</u></p>
<p>Pentru a înțelege tema, este necesară o scurtă descriere a calelor plan paralele, ce sunt, la ce sunt folosite și cum funcționează ele.</p>
<p>Conform NIST (National Institute of Standards and Technology)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, o cală plan paralelă este o piesă folosită ca standard de lungime ce are 2 laturi opuse plane și paralele.</p>
<p>Calele plan paralele au valori nominale în sistem metric (mm) și în sistem imperial (1 inch = 25.4 mm).</p>
<p>Ele sunt folosite pentru a produce diverse dimensiuni foarte precise care sunt folosite la calibrarea utilajelor industriale sau pentru verificarea instrumentelor de precizie.</p>
<p>Modul prin care aceste dimensiuni sunt obținute se numește „calare” și este una din proprietățile de bază, definitorie a acestor instrumente.</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://www.elastocon.com/learn-more/about-calibration/gauge-blocks-the-foundation-to-all-modern-industrial-production"><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2003.png" class="img-fluid figure-img"></a></p>
<figcaption class="figure-caption">Fig.3 Cale plan paralele (sistem metric)</figcaption>
</figure>
</div>
<p><br></p>
<ul>
<li><p><u>b) Calarea calelor plan paralele</u></p>
<p>Modul în care diverse dimensiuni pot fi obținute cu aceste cale se numește „calare” și poate fi definit ca procesul prin care două suprafețe aderă strâns una de cealaltă în absența mijloacelor externe (nu sunt magnetizate sau lipite împreună cu un adeziv).</p>
<p>Datorită fețelor lor extrem de plane, când două cale sunt calate, ele se „lipesc”.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="http://www.starrett-webber.com/gb46.html"><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2004.png" class="img-fluid figure-img"></a></p>
<figcaption class="figure-caption">Fig.4 Procedeul de calare a 2 cale</figcaption>
</figure>
</div>
<p>Repetând acest proces, pot fi calate consecutiv mai multe cale, obținând diverse dimensiuni.</p>
<p>De exemplu, dacă vrem să obținem dimensiunea de 1.8324″, putem cala împreună următoarele cale:</p>
<p>1.8324 = .1004 + .132 + .6 + 1 (obținem 1.8324 prin calarea a 4 cale)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://en.wikipedia.org/wiki/Gauge_block#/media/File:Gauge_block_adhesion.jpg"><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2005.png" class="img-fluid figure-img"></a></p>
<figcaption class="figure-caption">Fig.5 Mai multe cale sunt calate pentru a obține o dimensiune. Se observă cum ele rămân lipite sub acțiunea gravitației.</figcaption>
</figure>
</div>
<p>Motivul pentru care acest fenomen are loc nu este pe deplin înțeles, câteva ipoteze fiind<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>:</p>
<ol type="1">
<li><p>Presiunea aerului din mediul înconjurător, deoarece aerul este presat atunci când blocurile sunt calate împreună.</p></li>
<li><p>Tensiunea superficială a uleiului sau a vaporilor de apă din aer acționează ca un lipici pentru a le ține împreună.</p></li>
<li><p>Când două suprafețe foarte plane sunt aduse în contact atât de strâns una cu cealaltă, acest lucru permite un schimb de electroni între atomii lor, ceea ce creează o forță moleculară atractivă (această forță va rămâne chiar și în vid sau dacă nu este prezent ulei sau apă pe suprafețe).</p></li>
</ol></li>
</ul>
<p><br></p>
<ul>
<li><p><u>c) Setul Ford-Johansson cu 81 de piese</u></p>
<p>Setul analizat în această lucrare este compus din 81 de piese, aranjate în 4 clase (serii) de mărimi. Componența este următoarea (toate dimensiunile sunt în inch, voi face abstracție de semnul ″):</p>
<p><br></p>
<p><b>Seria 1 (9 cale):</b></p>
<p>.1001, .1002, .1003, .1004, .1005, .1006, .1007, .1008, .1009</p>
<p><br> <b>Seria 2 (49 cale):</b></p>
<p>.101, .102, .103, .104, .105, .106, .107, .108, .109, .110, .111, .112, .113, .114, .115, .116, .117, .118, .119, .120, .121, .122, .123, .124, .125, .126, .127, .128, .129, .130, .131, .132, .133, .134, .135, .136, .137, .138, .139, .140, .141, .142, .143, .144, .145, .146, .147, .148, .149</p>
<p><br> <b>Seria 3 (19 cale):</b></p>
<p>.050, .100, .150, .200, .250, .300, .350, .400, .450, .500, .550, .600, .650, .700, .750, .800, .850, .900, .950</p>
<p><br> <b>Seria 4 (4 cale):</b></p>
<p>1, 2, 3, 4</p>
<p><br> În total sunt 81 de piese, iar dacă le calăm pe toate împreună obținem (nominal) dimensiunea de <b>26.5295″</b>. <i>Această informație va fi importantă în această lucrare.</i></p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2006.jpg" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.6 Setul de 81 de piese realizat de C.E. Johansson pentru fabricile Ford pe care Ford însuși l-a făcut cadou bunului său prieten, Thomas Edison. Acum acest set se află la Muzeul Preciziei din Windsor, Vermont, Statele Unite ale Americii.</figcaption>
</figure>
</div>
<p><br></p>
</section>
<section id="enunțarea-problemei" class="level3">
<h3 class="anchored" data-anchor-id="enunțarea-problemei">1.3.2 Enunțarea problemei</h3>
<p>Pornind de la afirmațiile prezentate la punctul <a href="#1.1">1.1</a> (1.1.a și 1.1.b), punem următoarele întrebări:</p>
<ul>
<li><p>a) Având în vedere concluzia punctului 1.3.1.c (anume că dacă vom cala toate cele 81 de cale vom obține, nominal, dimensiunea de 26.5295″), <b>cum va arăta distribuția dimensiunilor pe care le putem obține în intervalul 0 – 26.5295?</b></p>
<p>Vom putea obține, cu aceeași rezoluție (aici rezoluție = pas) de 10<sup>-4</sup>, dimensiuni după ce vom trece de 10″ ?</p>
<p>De exemplu, între 11″ și 20″ putem obține toate numerele mergând cu un pas de 0.0001″ (10<sup>-4</sup>)? Dar între 20″ și 24″ ? Există vreo dimensiune pe care nu o putem obține?</p></li>
<li><p>b) Afirmația 1.1.b ne spune că pot fi obținute peste 100 000 de dimensiuni folosind piesele acestui set.</p>
<p><b>Care este numărul precis de dimensiuni pe care le putem obține folosind piesele acestui set ?</b></p></li>
</ul>
<p><br></p>
</section>
<section id="1.3.3" class="level3">
<h3 class="anchored" data-anchor-id="1.3.3">1.3.3 Intuiție inițială</h3>
<p>Pentru a răspunde la întrebările pe care ni le punem este important să avem un punct de plecare, o intuiție inițială. Iar pornind de la aceasta, să demonstrăm riguros veridicitatea sau neveridicitatea ei.</p>
<p>Referitor la întrebarea 1.3.2.a, așteptarea este ca granulația (de 10<sup>-4</sup> inch) cu care obținem dimensiuni în intervalul .2″ - 10″ (conform afirmației 1.1.a) să nu se păstreze până la maximul intervalului (26.5295″).</p>
<p>Avem un număr finit (81) de cale iar măsurile pe care le construim sunt din ce în ce mai mari, ceea ce înseamnă că vom folosi din ce în ce mai multe cale. Intuim că la un moment dat nu vom avea destule pentru a putea reprezenta cu aceeași granulație (sau finețe) numerele în intervale mai ridicate (de exemplu 16″ - 22″). Altfel spus, ne așteptăm să existe salturi între anumite numere și o descreștere a distribuției lor.</p>
<div id="fig7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2007.jpg" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig. 7 Descriere schematică a intuiției prezentate mai sus. Dreptunghiurile reprezintă cantitatea de numere ce pot fi obținute în intervalul respectiv.</figcaption>
</figure>
</div>
<p><br></p>
</section>
<section id="considerente-pragmatice" class="level3">
<h3 class="anchored" data-anchor-id="considerente-pragmatice">1.3.4 Considerente pragmatice</h3>
<p>După satisfacerea curiozităților de natură combinatorică care au pornit de la aceste instrumente, lucrarea își propune să trateze modul în care ele sunt folosite în practică.</p>
<p>Vom intra pe tărâmul metrologiei și vom vedea cum instrumente statistice precum gradul de încredere, distribuția toleranței unei măsurători și a.m.d. sunt folosite pentru a determina precizia unei măsurători.</p>
<p>De asemenea, vom aduce în discuție gradele de precizie și cum putem alege instrumentele potrivite în funcție de precizia măsurătorilor pe care le facem în mod uzual.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://www.muelaner.com/metrology/#uncertainty"><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2008.png" class="img-fluid figure-img"></a></p>
<figcaption class="figure-caption">Fig.8 Toate măsurătorile au un grad de incertitudine iar cu cât marja de toleranță este mai mare, cu atât crește încrederea că măsurătoarea respectivă se încadrează în acea marjă de toleranță.</figcaption>
</figure>
</div>
<p>Un lucru foarte important pe care acest instrumente l-au asigurat și încă îl asigura este trasabilitatea unei măsurători.</p>
<p>La fel cum în matematică este important să construim demonstrații care au la bază axiomele unui sistem algebric, în metrologie este important să putem să trasăm parcursul unei măsurători până la laboratorul sau cala de precizie cu care a fost realizată.</p>
<p>O măsurătoare trasabilă este una care are un lanț neîntrerupt de etalonări care revin la standardul de referință primar, cu incertitudini calculate pentru fiecare calibrare. Incertitudinea de măsurare este moștenită de-a lungul lanțului de etalonări, astfel încât incertitudinea crește cu cât ne depărtăm de standardul de referință primar. Trasabilitatea de la referința primară, prin laboratoare de metrologie acreditate și până la departamentele de metrologie industrială asigură că toată lumea lucrează la standarde comune și cunoaște aceeași incertitudine a unei măsurători<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p><br></p>
</section>
<section id="considerente-istorice" class="level3">
<h3 class="anchored" data-anchor-id="considerente-istorice">1.3.5 Considerente istorice</h3>
<p>Până la sfârșitul secolului al XIX-lea, ideea pieselor interschimbabile începută de Eli Whitney<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> a fost acceptată de națiunile industriale ca model pentru producția industrială.</p>
<p>Unul dintre dezavantajele acestui nou sistem era că necesită un control strict al dimensiunii foarte multor piese diferite. Pentru fiecare erau nevoie de numeroase calibre cu care erau verificate și calibrate diferitele piese din producția industrială. Numărul de astfel de calibre a devenit foarte mare. Natura complexă de producere a lor precum și costurile de întreținere au adus cheltuieli semnificative industriașilor. Pasul major spre simplificarea acestei situații a fost făcut de C.E. Johannson, un mașinist suedez.</p>
<p>Ideea lui Johannson, formulată pentru prima dată în 1896, a fost să facă un set mic de calibre care ar putea fi combinate pentru a forma calibre compozite mai mari și de dimensiuni diverse astfel încât să reducă numărul de calibre necesare. De exemplu, dacă patru calibre de dimensiuni de 1 mm, 2 mm, 4 mm și 8 mm pot fi combinate în orice combinație, toate dimensiunile milimetrice de la 1 mm la 15 mm ar putea fi făcute numai din aceste patru calibre. Johannson a mai descoperit că, dacă două fețe opuse ale unei piese de oțel sunt foarte plane și paralele, acestea s-ar lipi împreună atunci când erau alunecate împreună (eventual ajutate de o cantitate foarte mică de ulei)<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>. Din această cauză aceste calibre, în România, sunt numite Cale Plan Paralele (în țările vorbitoare de limba engleză ele se numesc Gauge Blocks). În Statele Unite, ideea a fost adoptată cu entuziasm de Henry Ford. Atât de utile au fost pentru fabricile Ford aceste instrumente întrucât, când s-a ivit oportunitatea, Henry Ford a cumpărat fabrica lui C.E. Johansson în care acesta realiza Seturile de Cale Plan Paralele. Ford și Johansson au avut o colaborare reușită iar stima pe care marele industriaș i-o purta inventatorul suedez poate fi înțeleasă astfel: în biroul personal al lui Ford puteau să intre fără programare doar 2 oameni: fiul său și C.E. Johansson. Prin influența pe care Ford o avea, a popularizat utilizarea calelor plan paralele iar, în cele din urmă, acestea au fost adoptate ca standard de transfer pentru lungime în industrie.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2008a.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.9 C.E. Johansson ținând în mână un „baton” de cale</figcaption>
</figure>
</div>
<p><br></p>
<p>Fun fact: La vremea la care le-a creat, erau multe definiții diferite pentru 1 inch și nu era un consens universal. Era inch-ul tâmplarului, cizmarului, bucătarului. Fiind subdiviziunea unei dimensiuni definită după corpul uman (1 foot), este normal ca ea să difere de la loc la loc. Totuși, Johansson a fost primul<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> care a stabilit (prin calele sale plan paralele) ca dimensiunea unui inch să fie exact 25.4 mm. Și nu a spus nimănui asta. Ani mai târziu, probabil într-o mare parte datorită calelor plan parelele Johansson, în urma întâlnirilor realizate între 1950 – 1959, laboratoarele de metrologie din Statele Unite, Canada, Anglia, Australia și Africa de Sud au convenit să definească inch-ul ca 25.4 mm.</p>
<p><br></p>
<p><br></p>
</section>
</section>
</section>
<section id="problema-de-numărare" class="level1">
<h1>2. Problema de numărare</h1>
<p>Pus în termeni simpli, ceea ce vrem să știm este:</p>
<p>Toate numerele, cu până la 4 zecimale, din intervalul [0.2, 26.3295] pot fi reprezentate folosind piese din setul Ford-Johansson cu 81 de cale plan paralele?</p>
<p><u>Observație:</u> Capetele de început și final, anume [0, 0.2] și [26.3295, 26.5295] le vom trata separat la final deoarece, conform 1.1.a, acolo avem o granulație mai mică.</p>
<p><br></p>
<section id="abordarea-naivă" class="level2">
<h2 class="anchored" data-anchor-id="abordarea-naivă">2.1 Abordarea naivă</h2>
<p>În orice problemă, este important să începem de undeva cu pași oricât de mici.</p>
<p>Să luăm un număr x din intervalul [0.2, 26.3295], de exemplu <strong>8.2349</strong>. Vrem să calibrăm cuțitul de tăiere al unui utilaj astfel încât să rașcheteze precis la distanța de 8.2349 inch față de o placă suport.</p>
<p>Vrem să scădem din acestă dimensiune mărimi din cele enumerate la punctul 1.3.1.c și să ajungem la 0.</p>
<p>Un mod de a face acest lucru este:</p>
<ol type="1">
<li><p>Să plecăm de la mic la mare. Scăpăm de zecimale, scăpăm de ultima zecimală și tot așa, iterativ. Practic, facem 0 cifra din dreapta.</p>
<table class="table">
<thead>
<tr class="header">
<th>Scăpăm de partea fracționară</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8.2349</td>
<td>|</td>
<td>- .1009</td>
</tr>
<tr class="even">
<td>8.134</td>
<td>|</td>
<td>- .134</td>
</tr>
<tr class="odd">
<td>8</td>
<td></td>
<td></td>
</tr>
</tbody>
</table></li>
<li><p>Odată ce nu mai avem zecimale, vom avea un număr natural și putem începe să scădem numerele mari în ordine descrescătoare (începând cu cele din Seria 4 de la punctul 1.3.1.c, apoi Seria 3 și tot așa).</p>
<table class="table">
<thead>
<tr class="header">
<th>Scăpăm de partea întreagă</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8</td>
<td>|</td>
<td>- 4</td>
</tr>
<tr class="even">
<td>4</td>
<td>|</td>
<td>- 3</td>
</tr>
<tr class="odd">
<td>1</td>
<td>|</td>
<td>- 1</td>
</tr>
<tr class="even">
<td>0</td>
<td></td>
<td></td>
</tr>
</tbody>
</table></li>
</ol>
<p>Gata. Acum putem lua calele care corespund mărimilor de mai sus, să le calăm și să obținem dimensiunea 8.2349.</p>
<p>4 + 3 + 1 + .1009 + .134 = 8.2349</p>
<p>Am găsit mulțimea {.1009, .134, 1, 3, 4} a cărei sumă face 8.2349</p>
<div id="0" class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
(0)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dar în [0.2, 26.3295] sunt 261 296 numere (mergând cu pasul de 0.0001)</p>
</div>
</div>
<p>Ar dura prea mult să verificăm toate numerele manual. Neștiind dacă toate aceste numere pot fi obținute din cele 81 de piese, chiar și un script rulat pe calculator va avea probleme – ar putea rula la nesfârșit sau ar putea dura foarte mult până ce găsește combinația potrivită. Să luăm ca exemplu un număr ceva mai mare, <strong>19.3657</strong>.</p>
<p>Vrem să verificăm dacă o piesă pe care urmează să o folosim într-un mecanism de mare finețe are lungimea unei laturi precis de 19.3657 inch. Ruleta ne arată 19.4 inch, șublerul ne zice 19.366 (cu toleranță de +/- 0.001 inch), dar noi vrem să fim mai preciși. Când depășim anumite limite de precizie, măsurarea directă nu mai este de mare folos. Asta se întâmplă din cauza toleranțelor implicite pe care instrumentele de măsură (rulete, șublere, micrometre) le au. În acestă situație vom recurge la măsurarea prin comparație. Prin urmare vom folosi un instrument care detectează schimbări cuprinse între 0 și 0.0004 inch (ceas comparator), vom construi dimensiunea respectivă cu cale plan paralele și o vom compara cu piesa noastră (prin glisare pe o suprafață plană).</p>
<p>Pentru a obține numărul, vom folosi aceeași metodă ca mai sus:</p>
<ol type="1">
<li><table class="table">
<thead>
<tr class="header">
<th>Scăpăm de partea fracționară</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>19.3657</td>
<td>|</td>
<td>- .1007</td>
</tr>
<tr class="even">
<td>19.265</td>
<td>|</td>
<td>- .115</td>
</tr>
<tr class="odd">
<td>19.15</td>
<td>|</td>
<td>- .15</td>
</tr>
<tr class="even">
<td>19</td>
<td></td>
<td></td>
</tr>
</tbody>
</table></li>
<li><table class="table">
<thead>
<tr class="header">
<th>Scăpăm de partea întreagă</th>
<th></th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>19</td>
<td>|</td>
<td style="text-align: center;">- 4</td>
</tr>
<tr class="even">
<td>15</td>
<td>|</td>
<td style="text-align: center;">- 3</td>
</tr>
<tr class="odd">
<td>12</td>
<td>|</td>
<td style="text-align: center;">- 2</td>
</tr>
<tr class="even">
<td>10</td>
<td>|</td>
<td style="text-align: center;">- 1</td>
</tr>
<tr class="odd">
<td>9</td>
<td>|</td>
<td style="text-align: center;">- .95</td>
</tr>
<tr class="even">
<td>8.05</td>
<td>|</td>
<td style="text-align: center;">- .9</td>
</tr>
<tr class="odd">
<td>7.15</td>
<td>|</td>
<td style="text-align: center;">- .85</td>
</tr>
<tr class="even">
<td>6.3</td>
<td>|</td>
<td style="text-align: center;">- .8</td>
</tr>
<tr class="odd">
<td>5.5</td>
<td>|</td>
<td style="text-align: center;">- .75</td>
</tr>
<tr class="even">
<td>4.75</td>
<td>|</td>
<td style="text-align: center;">- .7</td>
</tr>
<tr class="odd">
<td>4.05</td>
<td>|</td>
<td style="text-align: center;">- .65</td>
</tr>
<tr class="even">
<td>3.4</td>
<td>|</td>
<td style="text-align: center;">- .6</td>
</tr>
<tr class="odd">
<td>2.8</td>
<td>|</td>
<td style="text-align: center;">- .55</td>
</tr>
<tr class="even">
<td>2.25</td>
<td>|</td>
<td style="text-align: center;">- .5</td>
</tr>
<tr class="odd">
<td>1.75</td>
<td>|</td>
<td style="text-align: center;">- .45</td>
</tr>
<tr class="even">
<td>1.3</td>
<td>|</td>
<td style="text-align: center;">- .4</td>
</tr>
<tr class="odd">
<td>0.9</td>
<td>|</td>
<td style="text-align: center;">- .35</td>
</tr>
<tr class="even">
<td>0.55</td>
<td>|</td>
<td style="text-align: center;">- .3</td>
</tr>
<tr class="odd">
<td>0.25</td>
<td>|</td>
<td style="text-align: center;">- .25</td>
</tr>
<tr class="even">
<td>0</td>
<td></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table></li>
</ol>
<p><br></p>
<p>Vedem că în acest caz am fost norocoși iar calele s-au aliniat bine, chiar în ordine descrescătoare. Față de primul exemplu unde am folosit 5 cale pentru a obține dimensiunea dorită, aici am avut nevoie să folosim <strong>22</strong> de cale!</p>
<div id="1" class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Remarcăm și reținem: Dacă am folosit <strong>n</strong> cale ca să obținem un număr <strong>x</strong>, atunci calele rămase vor suma la numărul 26.5295 – <strong>x</strong> . <span id="eq-b"><span class="math display">\[         \tag{1}\]</span></span></p>
</div>
</div>
</div>
<p>Această simetrie va fi importantă în continuare.</p>
<p><br></p>
</section>
<section id="formulare-matematică" class="level2">
<h2 class="anchored" data-anchor-id="formulare-matematică">2.2 Formulare matematică</h2>
<p>Definim seriile de mărimi Si conform celor de la punctul 1.3.1.c.</p>
<p><span class="math display">\[Fie\ \mathcal{S}_\mathcal{i},\ i=\overline{1,4},\ multimi\ discrete\ definite\ astfel:\]</span> <span class="math display">\[\qquad\mathcal{S}_1=\overline{1,9}\cdot\left(0.0001\right)+\left(0.1\right),\ |\mathcal{S}_1|=9\]</span><br>
<span class="math display">\[\qquad\mathcal{S}_2=\overline{1,49}\cdot\left(0.001\right)+\left(0.1\right),\ |\mathcal{S}_2|=49\]</span><br>
<span class="math display">\[\qquad\mathcal{S}_3=\overline{1,19}\cdot\left(0.05\right),\ |\mathcal{S}_3|=19\]</span><br>
<span class="math display">\[\qquad\mathcal{S}_4=\overline{1,4},\ |\mathcal{S}_4|=4\]</span><br></p>
<p><span class="math display">\[Fie\ \mathcal{S}=\bigcup_{i=1}^{4}S_i,\ |\mathcal{S}|=81,\ \ \ \ \ \ \ \ \ Observatie:\sum\mathcal{S}=\sum_{x\in\mathcal{S}}x=26.5295\]</span></p>
<p><span class="math display">\[Clarificare: Multimea\ \mathcal{S}\ este\ reprezentarea\ setului\ Ford-Johansson\ cu\ 81\ de\ piese\]</span><br></p>
<p><span id="eq-2"><span class="math display">\[Fie\ \mathrm{\mathrm{X}}=\{x:x\in\left[0.2,\ 26.3295\right],\ x\cdot{10}^4\in\mathbb{N}\} \tag{2}\]</span></span></p>
<p><span class="math display">\[Aratati\ ca\ \forall\ {x}\in\mathrm{X},\ \exists\ \mathrm{S}_x=\{s_1, s_2,...,s_n\}\subseteq\mathcal{S},\ 0\leq{n}\leq81,\ a.i. \]</span> <span class="math display">\[\sum\mathrm{S}_x=\sum_{i=1}^{n}s_i=x\]</span></p>
<p><br></p>
</section>
<section id="reducere" class="level2">
<h2 class="anchored" data-anchor-id="reducere">2.3 Reducere</h2>
<p>Din <a href="#1">(1)</a> avem că:</p>
<p><span id="eq-3"><span class="math display">\[\displaylines{\forall\ {x}\in\mathrm{X},\ daca\ \exists\ \mathrm{S}_x\subseteq\mathcal{S}\ a.i. \sum\mathrm{S}_x=x\ si\ y:=26.5295-x, \\ atunci\ \exists\ \mathrm{S}_{y}=\mathcal{S}\setminus\mathrm{S}_x\ \ a.i.\ \sum\mathrm{S}_{y}=26.5295-x=y} \tag{3}\]</span></span></p>
<p>Exemplu:</p>
<p><span class="math display">\[x=4.5,\ \mathrm{S}_x=\{4, .5\},\ \sum\mathrm{S}_x=4.5=x\]</span></p>
<p><span class="math display">\[y=26.5295-x=26.5295-4.5=22.0295\]</span></p>
<p><span class="math display">\[\mathrm{S}_{y}=\mathcal{S}\setminus\mathrm{S}_x,\  \sum\mathrm{S}_{y}=\sum\mathcal{S}-\sum\mathrm{S}_x=26.5295-4.5=22.0295=y\]</span></p>
<p>Asta înseamnă că putem folosi simetria pentru a reduce la jumătate problema. Această simetrie poate fi văzută ca simetria dintre adunare și scădere. Pentru a obține o dimensiune din prima jumătate a intervalului, pornim de la 0 (nu avem nici o cală) și adunăm cale, iar pentru a obține simetricul acelei dimensiuni, pornim de la maxim (avem toate calele lipite) și scădem aceleași cale pe care le adunasem inițial.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2009.jpg" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.10 Schema structurii simetrice a intervalului studiat.</figcaption>
</figure>
</div>
<p><br></p>
</section>
<section id="ajustarea-intuiției-inițiale" class="level2">
<h2 class="anchored" data-anchor-id="ajustarea-intuiției-inițiale">2.4 Ajustarea intuiției inițiale</h2>
<p>Reamintindu-ne intuiția inițială (punctul <a href="#1.3.3">1.3.3</a>) și descrierea realizată în <a href="#fig7">Fig.7</a>, ne dăm seama că acum, cu informația de la punctul anterior, lucrurile vor sta altfel.</p>
<p>Prin urmare, îmbogățim și ajustăm intuiția astfel: poate că după 10″ distribuția dimensiunilor va scădea (trebuie demonstrat acest lucru), dar cu siguranță structura distribuției, per ansamblu, este simetrică față de mijlocul intervalului [0, 26.5295].</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2010.jpg" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.11 Descriere schematică a intuiției ajustate.</figcaption>
</figure>
</div>
<p>Acest lucru ne ușurează sarcina. Considerând adevărată afirmația din alegerea temei (1.1.a), ne rămâne să extindem afirmația 1.1.a de la 10″ până la 13.2647″ și, prin simetrie, va rezulta că toate numerele cu până la 4 zecimale din intervalul [0.2, 26.3295] pot fi obținute cu piese din acest set.</p>
<p><br></p>
</section>
<section id="reformulare-și-rezolvare" class="level2">
<h2 class="anchored" data-anchor-id="reformulare-și-rezolvare">2.5 Reformulare și rezolvare</h2>
<p><a href="#eq-2">(2)</a> devine:</p>
<p><span class="math display">\[Fie\ \hat{\mathrm{X}}=\{x:x\in\left[0.2,\ 13.2647\right],\ x\cdot{10}^4\in\mathbb{N}\}\]</span></p>
<p><span id="eq-4"><span class="math display">\[\displaylines{Aratati\ ca\ \forall\ {x}\in\hat{\mathrm{X}},\ \exists\ \mathrm{S}_x=\{s_1, s_2,...,s_n\}\subseteq\mathcal{S},\ 0\leq{n}\leq81,\ a.i. \\ \sum\mathrm{S}_x=\sum_{i=1}^{n}s_i=x} \tag{4}\]</span></span></p>
<p><u><strong>Rezolvare:</strong></u></p>
<p>Idee:</p>
<ol type="i">
<li><p>Arătăm că putem obține un inch complet (aici prin „complet” înțelegem că putem merge „continuu” cu pas de 0.0001).Vom arăta acest lucru pentru intervalul [0.2, 1.1999].</p></li>
<li><p>Arătăm că putem obține orice număr natural între 1 și 13 folosind piesele rămase după ce am scos cele pe care le-am folosit la punctul i).</p></li>
</ol>
<p>Din i) și ii) rezultă că putem acoperi tot intervalul <strong>X</strong>.</p>
<p><br></p>
<p>i.</p>
<p><span class="math inline">\(a)\ Aratam\ ca\ (4)\ este\ valabil\ pentru\ intervalul\ [0.2, 0.9999]:\)</span><br><br></p>
<p><span class="math display">\[Fie\ x:=\overline{0.abcd},\ b,c,d\in\overline{0,9},\ a\in\overline{2,9}\]</span><br></p>
<p><span class="math inline">\(\qquad a.1)\ daca\ d=0,\ continua\ la\ pasul\ a.2),\ altfel:\)</span></p>
<p><span class="math display">\[\forall\ d\in\overline{1,9},\ \exists\ s_1\in\mathcal{S}_1\ a.i.\]</span></p>
<p><span class="math display">\[ x_1:=x-s_1=\overline{0.(a-1)bc},\ (a-1)\in\overline{1,8}\]</span></p>
<p><span class="math inline">\(\qquad a.2)\ daca\ \overline{bc}\equiv0\ (mod\ 50),\ continua\ la\ pasul\ a.3),\ altfel:\)</span></p>
<p><span class="math display">\[\forall\ \overline{bc}\in\overline{1,49},\ \exists\ s_2\in\mathcal{S}_2\ a.i.\]</span></p>
<p><span class="math display">\[x_2:=x_1-s_2=\begin{cases} \overline{0.(a-2)5}\quad \\ \quad sau \\ \overline{0.(a-2)} \end{cases},\ (a-2)\in\overline{0,7}\]</span></p>
<p><span class="math inline">\(\qquad a.3)\ daca\ x_2=0,\ gata, altfel:\)</span></p>
<p><span class="math display">\[\forall\ (a-2)\in\overline{0,7},\ \exists\ s_3\in \mathcal{S}_3\ a.i.\]</span> <span class="math display">\[x_2-s_3=0\]</span></p>
<p><span class="math inline">\(\qquad Prin\ urmare,\ putem\ construi\ \mathrm{S}_x=\{s_1\in\mathcal{S}_1, s_2\in\mathcal{S}_2, s_3\in\mathcal{S}_3\}\ a.i.\)</span><br><br> <span class="math display">\[ \sum\mathrm{S}_x=x,\ \forall\ x\in[0.2, 0.9999]\]</span> <br></p>
<p><span class="math inline">\(\qquad\underline{Observatie}:\ \mathrm{S}_x\ are\ cel\ mult\ 3\ elemente,\ cate\ unul\ din\ \mathcal{S}_1,\ \mathcal{S}_2\ respectiv\ \mathcal{S}_3.\)</span></p>
<p><br></p>
<p><span class="math inline">\(b)\ Aratam\ ca\ (4)\ este\ valabil\ pentru\ intervalul\ [1, 1.199]:\)</span><br><br></p>
<p><span class="math display">\[Fie\ x:=\overline{1.abcd},\ b,c,d\in\overline{0,9},\ a\in\{0,1\}\]</span><br></p>
<p><span class="math inline">\(\qquad b.1)\ daca\ d=0,\ continua\ la\ pasul\ b.2),\ altfel:\)</span></p>
<p><span class="math display">\[\forall\ d\in\overline{1,9},\ \exists\ s_1\in\mathcal{S}_1\ a.i.\]</span></p>
<p><span class="math display">\[ x_1:=x-s_1=\begin{cases} \overline{0.9bc}\\ \ sau\\ \overline{1.0bc}\end{cases}\]</span></p>
<p><span class="math inline">\(\qquad b.2)\ daca\ \overline{bc}\equiv0\ (mod\ 50),\ continua\ la\ pasul\ b.3),\ altfel:\)</span></p>
<p><span class="math display">\[\forall\ \overline{bc}\in\overline{1,49},\ \exists\ s_2\in\mathcal{S}_2\ a.i.\]</span></p>
<p><span class="math display">\[x_2:=x_1-s_2=\begin{cases} \begin{cases}0.85\\sau\\0.8\end{cases}\quad \\ \quad sau \\\begin{cases}0.95\\sau\\0.9\end{cases}\end{cases}\]</span></p>
<p><span class="math inline">\(\qquad b.3)\ \exists\ s_3\in\{.8, .85, .9, .95, 1\}\ a.i.\ x_2-s_3=0\)</span><br><br></p>
<p><span class="math inline">\(\qquad Prin\ urmare,\ putem\ construi\ \mathrm{S}_x=\{s_1, s_2, s_3\}\ a.i.\)</span><br><br> <span class="math display">\[\sum\mathrm{S}_x=x,\ \forall\ x\in[1, 1.1999]\]</span></p>
<p>Din a) și b) rezultă că putem construi fiecare număr cu până la 4 zecimale în intervalul [0.2, 1.1999]. <br><br></p>
<p>ii.</p>
<p>Pentru punctul i) folosim cel mult 3 cale, câte una din Seria 1, Seria 2 sau Seria 3. Asta înseamnă că putem folosi complet Seria 4 = {1, 2, 3, 4} cu care putem genera numerele naturale de la 1 la 10 inclusiv.</p>
<p>Vrem să generăm pe 11, 12 și 13. Facem observația că din Seria 3 folosim doar 1 singură cală la punctul i), prin urmare ne rămân 18 cale în Seria 3 pe care le putem folosi. Remarcăm că putem aranja calele din Seria 3 astfel:</p>
<table class="table">
<colgroup>
<col style="width: 42%">
<col style="width: 18%">
<col style="width: 21%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Gruparea calelor din Seria 3</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.05 + .95 = 1</td>
<td>.1 + .9 = 1</td>
<td>.15 + .85 = 1</td>
<td>.2 + .8 = 1</td>
</tr>
<tr class="even">
<td>.25 + .75 = 1</td>
<td>.3 + .7 = 1</td>
<td>.35 + .65 = 1</td>
<td>.4 + .6 = 1</td>
</tr>
<tr class="odd">
<td>.45 + .55 = 1</td>
<td>.5</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Prin urmare, vom putea oricând lua 3 astfel de perechi pe care să le adunăm la calele din Seria 4 astfel încât să generăm toate numerele naturale de la 1 la 13.</p>
<p>Acum vom spune că:</p>
<p><span class="math display">\[\ \forall\ x\in\hat{\mathrm{X}}=\{x:x\in\left[0.2,\ 13.2647\right],\ x\cdot{10}^4\in\mathbb{N}\},\]</span></p>
<p><span class="math display">\[\exists!\ (a,b)\ cu\ a\in\overline{1,13}\ \cup \{0\}\ si\ b\in\{x:x\in[0.2, 1.1999],\ x\cdot10^4\in\mathbb{N}\}\ a.i.\]</span></p>
<p><span class="math display">\[\begin{cases}a+b=x \\ din\ i):\quad \forall\ b,\ \exists\ \mathrm{S}_b\subseteq\mathcal{S}\ a.i.\ \sum\mathrm{S}_b=b \\ din\ ii):\quad \forall\ a,\ \exists\ \mathrm{S}_a\subseteq\mathcal{S},\ \mathrm{S}_a\cap\mathrm{S}_b=∅\ a.i.\ \sum\mathrm{S}_a=a \end{cases}\quad \Rightarrow\]</span></p>
<p><br></p>
<p><span class="math display">\[⇒\ \forall\ x\in\hat{\mathrm{X}},\ \exists\ \mathrm{S}_x=(\mathrm{S}_a\cup\mathrm{S}_b)\subseteq\mathcal{S},\ a.i. \\ \]</span> <span id="eq-5"><span class="math display">\[\sum\mathrm{S}_x=\sum\mathrm{S}_a+\sum\mathrm{S}_b=a+b=x \tag{5}\]</span></span></p>
<p><br></p>
<p>Final:</p>
<p><span class="math display">\[\forall\ x\in\hat{\mathrm{X}},\ putem\ construi\ y:=26.5295-x,\ y\in\mathrm{Y}=26.5295-\mathrm{X},\]</span></p>
<p><span class="math display">\[\mathrm{Y}=\{y:y\in\left[13.2648,\ 26.3295\right],\ y\cdot{10}^4\in\mathbb{N}\}.\]</span></p>
<p><span id="eq-6"><span class="math display">\[din\ (3):\ \forall\ y\in\mathrm{Y},\ \exists\ \mathrm{S}_y\subseteq\mathcal{S},\ a.i.\ \sum\mathrm{S}_y=y. \tag{6}\]</span></span></p>
<p><span id="eq-7"><span class="math display">\[Observam\ ca\ \ \mathrm{Y}\ \cup\ \hat{\mathrm{X}}=\mathrm{X}. \tag{7}\]</span></span><br></p>
<p><span class="math display">\[\displaylines{Din\ (5),\ (6),\ (7)\ ⇒ \forall\ {x}\in\mathrm{X}=\{x:\ x\in[0.2, 26.3295],\ x\cdot10^4\in\mathbb{N}\},\\ \exists\ \mathrm{S}_x=\{s_1, s_2,...,s_n\}\subseteq\mathcal{S},\ 0\leq{n}\leq81,\ a.i. }\]</span> <span class="math display">\[\sum\mathrm{S}_x=\sum_{i=1}^{n}s_i=x\]</span></p>
<p>Ceea ce trebuia demonstrat.</p>
<p><br></p>
</section>
<section id="capete" class="level2">
<h2 class="anchored" data-anchor-id="capete">2.6 Capete</h2>
<p>Ca să acoperim complet intervalul [0, 26.5295], mai trebuie să vedem ce se întâmplă pe capete (intervalele [0, 0.2) și (26.3295, 26.5295] ).</p>
<p>Acolo lucrurile sunt mai simple deoarece nu avem o granulație așa de fină. Este în continuare valabilă observația cu simetria.</p>
<p>[0, 0.1) – avem 2 mărimi: 0 și cala de .05 (considerăm 0 ca fiind o mărime valabilă)</p>
<p>[0.1, 0.2) – avem 118 mărimi:</p>
<ul>
<li><p>100 de mărimi fiind cele obținute cu calele din Seria 2 și cala de .05:</p>
<ul>
<li>.100, .101, .102, .103, …. , .198, .199</li>
</ul></li>
<li><p>18 mărimi fiind cele obținute cu calele din Seria 1 și cala de .05:</p>
<ul>
<li>.1001, .1002, … , .1009, .1051, .1052, … , .1059</li>
</ul></li>
</ul>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Prin urmare, în fiecare capăt putem obține 120 de măsuri, deci 240 în total.<span id="eq-8"><span class="math display">\[         \tag{8}\]</span></span></p>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="concluzii" class="level2">
<h2 class="anchored" data-anchor-id="concluzii">2.7 Concluzii</h2>
<p>Am plecat de la aceste 2 afirmații:</p>
<ol type="a">
<li><p>„ Folosind piesele acestui set, se pot obține măsuri între 0.1″ și 0.2″ cu pas de 0.001″ și între 0.2″ și 10″ cu pas de 0.0001″ ” (traducere personală din Fig 2.)</p></li>
<li><p>„ Mai mult de 100 000 de combinații sunt posibile folosind acest set cu 81 de piese ” (traducere personală din Fig 2.)</p></li>
</ol>
<p>Și ne-am propus să le dăm o formă completă. Acum putem spune:</p>
<ol type="a">
<li><p>Folosind piesele acestui set, se pot obține:</p>
<ol type="1">
<li><p>Măsuri între 0.1″ și 0.2″ cu pas de 0.001″</p></li>
<li><p>Măsuri între 0.2″ și 26.3295″ cu pas de 0.0001″</p></li>
<li><p>Măsuri între 26.3295″ și 26.5295″ cu pas de 0.001″</p></li>
</ol>
<p>Din (0) și (8) putem obține numărul total de mărimi pe care le putem construi cu acest set cu 81 de cale, iar afirmația b) devine:</p></li>
<li><p>Cu acest set pot fi construite exact <strong>261 536</strong> mărimi diferite (incluzând mărimea 0)</p></li>
</ol>
<p>Pentru a arăta acest lucru a fost foarte importantă vizualizarea problemei și înțelegerea naturii ei simetrice. Putem vedea cum intuiția a evoluat și, pe măsură ce noi observații au fost făcute, intuiția s-a adaptat, a descoperit mai multe unghiuri de a vedea problema.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2011.jpg" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.12 Evoluția intuiție pe parcursul realizării acestei lucrări.</figcaption>
</figure>
</div>
<p><br></p>
<p>Remarcăm faptul că oamenii consulați în timpul redactării acestei lucrări aveau același „feeling”, anume că anumite mărimi nu pot fi obținute. Mai mult, videoclipul de la care a plecat această lucrare și care își punea aceleași întrebări, oferă în final său un răspuns legat de numărul total de mărimi ce pot fi obținute cu acest set – 230 682<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>, număr ce este contrazis de lucrarea mea.<br></p>
</section>
</section>
<section id="optimizare-și-algoritm" class="level1">
<h1>3. Optimizare și algoritm</h1>
<p>Observăm că demonstrația de mai sus oferă o metodă explicită de a obține o măsură. Spunem că putem obține măsurile din prima jumătate iar cele din jumătatea rămasă sunt, pentru fiecare, totalul minus măsura corespondentă din prima jumătate.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2012.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.13 Când construim o măsura X, rămâne măsura Total – X</figcaption>
</figure>
</div>
<p>Totuși, acest mod, deși corect, nu oferă tot timpul combinația optimă prin care putem obține o măsură. Prin optim înțelegem combinația care are numărul minim de cale.</p>
<p><br></p>
<p>De exemplu:</p>
<p>Folosind algoritmul folosit în demonstrația problemei la punctul 2.5, putem obține ultimul număr din prima jumătate, anume 13.2647, în felul următor:</p>
<table class="table">
<thead>
<tr class="header">
<th>.</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>13.2647</td>
<td>|</td>
<td>- .1007</td>
</tr>
<tr class="even">
<td>13.164</td>
<td>|</td>
<td>- .114</td>
</tr>
<tr class="odd">
<td>13.05</td>
<td>|</td>
<td>- .05</td>
</tr>
<tr class="even">
<td>13</td>
<td>|</td>
<td>- 4</td>
</tr>
<tr class="odd">
<td>9</td>
<td>|</td>
<td>- 3</td>
</tr>
<tr class="even">
<td>6</td>
<td>|</td>
<td>- 2</td>
</tr>
<tr class="odd">
<td>4</td>
<td>|</td>
<td>- 1</td>
</tr>
<tr class="even">
<td>3</td>
<td>|</td>
<td>- .95</td>
</tr>
<tr class="odd">
<td>2.05</td>
<td>|</td>
<td>- .9</td>
</tr>
<tr class="even">
<td>1.15</td>
<td>|</td>
<td>- .85</td>
</tr>
<tr class="odd">
<td>0.3</td>
<td>|</td>
<td>- .3</td>
</tr>
<tr class="even">
<td>0</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Obținem 13.2647 folosind cele 11 cale de mai sus. Din <a href="#eq-3">(3)</a> conform simetriei, numărul 13.2648 = 26.5295 – 13.2647 este obținut de cele 70 de cale rămase nefolosite din setul de 81. Dar acest număr este chiar următorul și putem vedea că poate fi obținut, defapt, tot cu 11 cale, înlocuind cala .1007 cu .1008.</p>
<p>Prin urmare, este legitimă întrebarea:</p>
<p><strong>Cum putem obține combinațiile optime pentru fiecare număr?</strong></p>
<p><br></p>
<section id="optimizare" class="level2">
<h2 class="anchored" data-anchor-id="optimizare">3.1 Optimizare</h2>
<p>Vrem ca atunci când construim o măsura, să folosim combinația care are cele mai puține cale în compoziție. Acest lucru este de dorit mai ales din motive practice. Este mai ușor să calăm un număr mai mic de piese decât unul mai mare. De asemenea, aceste piese de mare precizie, calele plan paralele, au totuși niște toleranțe. În funcție de gradul de precizie din care fac parte, calarea mai multor cale va scădea gradul de încredere al acurateței combinației.</p>
<p>Din nou, este important să simplificăm problema. Uitându-ne la seria cu cele mai mari cale, Seria 4, are calele: 1, 2, 3, 4. Ce este o combinație optimă pentru acest set?</p>
<p><br></p>
<p><u>De exemplu:</u></p>
<p>Cu piesele din {1, 2, 3, 4} putem obține mulțimea {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}.</p>
<p>Să spunem că vrem să-l construim pe 8.</p>
<ol type="1">
<li><p>8 nu se află în S4 = {1, 2, 3, 4}, mergem mai departe</p></li>
<li><p>Facem combinații de câte două elemente și verificăm la cât sumează. Cu mențiunea că nu ne interesează valorile pe care le-am verificat deja la pasul anterior.</p>
<p>{1,2} = 3, {1,3} = 4, {1,4} = 5, {2,3} = 5, {2,4} = 6, {3,4} = 7</p>
<p>Tot nu îl găsim pe 8. Mergem mai departe</p></li>
<li><p>Facem combinații de câte trei elemente și verificăm la cât sumează.</p>
<p>{1,3,4} = 8, {2, 3, 4} = 9</p>
<p>Gata, l-am găsit pe 8, poate fi construit cu {1,3,4}</p></li>
</ol>
<div id="fig13" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2013.jpg" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.14 Vizualizare schematică a modului de căutare a combinației optime.</figcaption>
</figure>
</div>
<p><br></p>
<p><u>Observație:</u></p>
<p>Această metodă de parcurgere implică, defapt, parcurgerea pe nivele a „power-setului” lui S4, în acest caz o mulțime cu 2<sup>S4</sup> = 2<sup>|S4|</sup> = 2<sup>4</sup> = 16 submulțimi.</p>
<p>Generalizând acest raționament, pentru un număr construibil x, combinația optimă va fi primul nivel din arborele generat de 𝒫(S) (unde S este setul de 81 de piese) în care găsim mulțimea care sumează la x. „Etajul” la care ne vom afla va fi numărul de cale pe care le va avea combinația, iar acest număr va fi minim, prin urmare combinația va fi optimă.</p>
<p><br></p>
<p>Ca să găsim combinația optimă a unui nr construibil x, pașii pe care îi vom face vor fi:</p>
<ol type="1">
<li><p>Caută-l pe x în mulțimea inițială. Dacă existră – stop, altfel continuă:</p></li>
<li><p>Caută-l pe x în mulțimea sumelor submulțimilor de 2 elemente.</p></li>
<li><p>Caută-l pe x în mulțimea sumelor submulțimilor de 3 elemente.</p></li>
<li><p>Tot așa, continuă până îl găsești pe x.</p></li>
</ol>
<p>Dar în cazul setului nostru ar însemnă să trecem prin până la 2<sup>81</sup> mulțimi, ceea ce este mult.</p>
<p><br></p>
<p>Întorcându-ne la demonstrație, la punctul <a href="#reformulare-și-rezolvare">2.5</a> am arătat că putem construi 1 inch complet din maxim 3 piese.</p>
<p>Deci un număr va fi construit din: (maxim 3 piese) + piesele cu care construim partea întreagă. <br></p>
<p>Din nou, vorbim despre o abordare în 2 pași:</p>
<ol type="i">
<li><p>Construim partea fracționară cu maxim 3 piese</p></li>
<li><p>Construim partea întreagă</p></li>
</ol>
<p>Înainte de a scrie pseudocodul va trebui să clarificăm faptul că este necesar ca cele 4 serii de mărimi să fie definite ca 4 liste/vectori și să fie ordonate crescător. Primul element din listă are indicele 0.</p>
<p><br></p>
<p>Definim s1, s2, s3, s4 conform <a href="#definirea-datelor-problemei">1.3.1</a> punctul c) (aici s1 ~ set1, șamd).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>set1 <span class="op">=</span> [x<span class="op">/</span><span class="dv">10000</span> <span class="cf">for</span> x <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1001</span>, <span class="dv">1010</span>)]</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>set2 <span class="op">=</span> [x<span class="op">/</span><span class="dv">10000</span> <span class="cf">for</span> x <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1010</span>, <span class="dv">1491</span>, <span class="dv">10</span>)]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>set3 <span class="op">=</span> [x<span class="op">/</span><span class="dv">10000</span> <span class="cf">for</span> x <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">500</span>, <span class="dv">9501</span>, <span class="dv">500</span>)]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>set4 <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>ss <span class="op">=</span> set1 <span class="op">+</span> set2 <span class="op">+</span> set3 <span class="op">+</span> set4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol type="i">
<li><p>Folosim pașii pe care i-am folosit în demonstrație :</p>
<p>1. <strong>def</strong> funcție(nr, s1, s2, s3, s4):</p>
<p>2. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;comb = listă goală</p>
<p>3. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n1 = (ultima cifra a lui nr) - 1</p>
<p>4. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>daca</strong> n1 != -1:</p>
<p>5. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>scade</strong> piesa s1[n1] <strong>din</strong> nr</p>
<p>6. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>adaugă</strong> s1[n1] <strong>în</strong> comb</p>
<p>7. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>elimina</strong> s1[n1] <strong>din</strong> s1</p>
<p>8. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n2 = ((ultimele 2 cifre ale lui nr) modulo 50) – 1</p>
<p>9. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>daca</strong> n2 != -1:</p>
<p>10. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>scade</strong> piesa s2[n2] <strong>din</strong> nr</p>
<p>11. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>adaugă</strong> s2[n2] <strong>în</strong> comb</p>
<p>12. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>elimina</strong> s2[n2] <strong>din</strong> s2</p>
<p>13. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n3 = ((ultimele 2 cifre ale lui nr)/5) – 1</p>
<p>14. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>daca</strong> n3 != -1:</p>
<p>15. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>scade</strong> piesa s3[n3] <strong>din</strong> nr</p>
<p>16. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>adaugă</strong> s3[n3] <strong>în</strong> comb</p>
<p>17. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>elimina</strong> s3[n3] <strong>din</strong> s3</p>
<p>În acest moment variabila <strong>nr</strong> va fi sigur un număr întreg.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># functia are parametrii numarul tinta si cele 4 serii de cale</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> func(nr, s1, s2, s3, s4):</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a> <span class="co"># aici 23.4 este limita obtinuta empiric de unde este mai</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a> <span class="co"># eficient (ca timp) sa construiesti numarul prin</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a> <span class="co"># construirea diferentei 26.5295-nr</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> nr<span class="op">&lt;</span><span class="fl">23.4</span>:</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    comb <span class="op">=</span> []</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    n1 <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">*</span><span class="dv">10000</span>)<span class="op">%</span><span class="dv">10</span><span class="op">-</span><span class="dv">1</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> n1<span class="op">!=-</span><span class="dv">1</span>:</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>      nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">-</span>s1[n1], <span class="dv">5</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>      comb.append(s1[n1])</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>      <span class="kw">del</span> s1[n1]</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    n2 <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">*</span><span class="dv">1000</span>)<span class="op">%</span><span class="dv">50</span><span class="op">-</span><span class="dv">1</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> n2<span class="op">!=-</span><span class="dv">1</span>:</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>      nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">-</span>s2[n2], <span class="dv">5</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>      comb.append(s2[n2])</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>      <span class="kw">del</span> s2[n2]</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    n3 <span class="op">=</span> <span class="bu">round</span>((<span class="bu">round</span>(nr<span class="op">*</span><span class="dv">100</span>)<span class="op">%</span><span class="dv">100</span>)<span class="op">/</span><span class="dv">5</span>)<span class="op">-</span><span class="dv">1</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> n3<span class="op">!=-</span><span class="dv">1</span> <span class="kw">and</span> n3<span class="op">&lt;</span><span class="dv">20</span>:</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>      nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">-</span>s3[n3], <span class="dv">5</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>      comb.append(s3[n3])</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>      <span class="kw">del</span> s3[n3]</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Pana aici am scapat de numerele de dupa virgula</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><br></p></li>
<li><p>Pentru partea întreagă:</p>
<p>Vom merge pe cazuri:</p>
<ol type="a">
<li><p>Partea întreagă =&lt; 10. Folosim Seria 4 = S4 = {1, 2, 3, 4}</p>
<p>Conform <a href="#fig13">Fig.13</a> am putea începe cu piese mari și să facem power setul Seriei 4. Va fi o metodă care va funcționa.</p>
<p>Dar în acest caz putem folosi o proprietate a Seriei 4:</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Seria 4 este o mulțime care poate fi generată prin adunări repetate ale unui singur element, anume <strong>1</strong>, care se află în seria 4.</p>
<p><span id="eq-9"><span class="math display">\[     \tag{9}\]</span></span></p>
</div>
</div>
</div>
<p>Această proprietate este importantă pentru că ne dă posibilitatea să construim direct mulțimea unui număr întreg, fără a mai fi nevoie să căutăm acea mulțime în arborele descris mai sus.</p>
<p><u>Exemplu:</u></p>
<p>Avem S4 = {1,2,3,4} – vrem să-l căutăm pe 8:</p>
<ol type="1">
<li><p>Care este prima piesă din S4 = {1, 2, 3, 4} care este =&lt; 8 ?</p>
<p>Răspuns: <strong>4</strong>. Scădem pe 4 din 8 și eliminăm 4 din S4.</p></li>
<li><p>Care este prima piesă din S4 = {1,2,3} care este =&lt; 4 ?</p>
<p>Răspuns: <strong>3</strong>. Scădem pe 3 din 4 și eliminăm pe 3 din S4.</p></li>
<li><p>Care este prima piesă din S4 = {1,2} care este =&lt; 1 ?</p>
<p>Răspuns: <strong>1</strong>. Scădem pe 1 din 1 și am ajuns la 0.</p></li>
</ol>
<p>Această metodă va funcționa tot timpul și este mai eficientă din punctul de vedere al timpului de execuție.</p>
<p><u>Obs.:</u> Dacă partea întreagă este mai mare decât 10, folosim complet Seria 4.</p>
<p>1. <strong>dacă</strong> nr &gt;= 10:</p>
<p>2. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>scade</strong> 10 <strong>din</strong> nr</p>
<p>3. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>adauga</strong> s4 <strong>în</strong> comb</p>
<p>4. <strong>altfel</strong>:</p>
<p>5. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>pentru</strong> i <strong>în</strong> [0, 1, 2, 3]:</p>
<p>6. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>dacă</strong> nr &gt; s4[3-i]:</p>
<p>7. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>scade</strong> piesa s4[3-i] <strong>din</strong> nr</p>
<p>8. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>adaugă</strong> s4[3-i] <strong>în</strong> comb</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> nr<span class="op">&gt;=</span><span class="dv">10</span> <span class="kw">or</span> <span class="dv">10</span><span class="op">-</span>nr<span class="op">&lt;</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="dv">5</span>):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>      comb.extend(s4)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>      nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">-</span><span class="dv">10</span>, <span class="dv">5</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      <span class="cf">for</span> i <span class="kw">in</span> [<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>]:</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> nr<span class="op">&gt;=</span>s4[<span class="dv">3</span><span class="op">-</span>i] <span class="kw">or</span> s4[<span class="dv">3</span><span class="op">-</span>i]<span class="op">-</span>nr<span class="op">&lt;</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="dv">5</span>):</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>          nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">-</span>s4[<span class="dv">3</span><span class="op">-</span>i], <span class="dv">5</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>          comb.append(s4[<span class="dv">3</span><span class="op">-</span>i])</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> nr<span class="op">==</span><span class="dv">0</span>:</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span>(comb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><br></p></li>
<li><p>Partea întreagă =&lt; ~ 19.5.</p>
<p>După ce epuizăm Seria 4, trecem la:</p>
<p><strong>Seria 3</strong> = {.050, .100, .150, .200, .250, .300, .350, .400, .450, .500, .550, .600, .650, .700, .750, .800, .850, .900, .950}</p>
<p>Această serie are mai multe cale decât Seria 4, dar structura este asemănătoare. Dacă dăm factor comun .05, Seria 3 devine:</p>
<p><strong>Seria 3</strong> = .05*{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}</p>
<p>Pentru că această mulțime are proprietatea <a href="#eq-9">(9)</a>, vom proceda asemănător.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> nr<span class="op">&gt;=</span><span class="bu">sum</span>(s3) <span class="kw">or</span> <span class="bu">sum</span>(s3)<span class="op">-</span>nr<span class="op">&lt;</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="dv">5</span>):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>      comb.extend(s3)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>      nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">-</span><span class="bu">sum</span>(s3), <span class="dv">5</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>      s3<span class="op">=</span>[]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>      <span class="cf">while</span> nr<span class="op">&gt;</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="dv">5</span>) <span class="kw">and</span> <span class="bu">len</span>(s3)<span class="op">!=</span><span class="dv">0</span>:</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        m3 <span class="op">=</span> <span class="bu">list</span>(<span class="bu">filter</span>(<span class="kw">lambda</span> i: s3[i] <span class="op">&lt;=</span> nr<span class="op">+</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="dv">5</span>), <span class="bu">range</span>(<span class="bu">len</span>(s3))))[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">-</span>s3[m3], <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><u>Obs.:</u> Este probabil ca în acest moment Seria 3 să nu fie completă și o piesă să fi fost folosită la punctul i) anterior. Acest lucru poate da naștere unor cazuri particulare precum:</p>
<ul>
<li><p>Am scăzând descrescător piese din S3 până am ajuns la piesa .35 iar nr = .4</p>
<p>Dacă voi scădea .35 din .4 voi rămâne cu .05. Dacă am folosit .05 în prima parte (punctul i ), atunci nu voi avea cum să obțin acel .05 cu nimic altceva (este cea mai mică piesă). Ideea e să te întorci și să continui cu .3 în loc de .35 și apoi cu .1</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">round</span>(nr<span class="op">-</span>s3[<span class="dv">0</span>], <span class="dv">3</span>)<span class="op">&lt;</span><span class="dv">0</span> <span class="kw">and</span> nr<span class="op">&gt;</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="dv">5</span>):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>          nr <span class="op">=</span> <span class="bu">round</span>(nr <span class="op">+</span> s3[m3], <span class="dv">5</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>          m3 <span class="op">-=</span> <span class="dv">1</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>          nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">-</span> s3[m3], <span class="dv">5</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        comb.append(s3[m3])</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="kw">del</span> s3[m3]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
</ul>
<p><br></p>
<p>Cu punctele ii.a) și ii.b) descrise până acum putem construi eficient și optim numere până la aprox. ~ 19.5.</p>
<p>Pentru numere mai mari, metodele pe care le-am folosit nu vor mai funcționa.</p>
<p><br></p></li>
<li><p>Partea întreagă &gt;= ~ 19.5</p>
<p>În acest punct, putem recurge la metoda recursivă descrisă în <a href="#fig13">Fig.13</a></p>
<p>Natura recursivă a acestei probleme împreună cu posibilitatea de a împărți problema în subprobleme ne indică să căutăm în direcția algoritmilor dinamici.</p>
<p>Căutând informații despre acest tip de probleme, aflăm următorul lucru:</p>
<ul>
<li><p>Problema noastră, obținerea unei submulțimi care sumează la un număr dat, este un caz particular al problemei <strong>Knapsack</strong><a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
<p>Pe scurt, problema Knapsack spune:</p>
<p>Având o mulțime de obiecte, fiecare cu o greutate și o valoare, ce combinație va umple un ghiozdan ce poate suporta o greutate maximă (knapsack), maximizând greutatea și valoarea?</p></li>
<li><p>Acest caz particular se numește <strong>Subset Sum Problem</strong><a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> și spune, pe scurt:</p>
<p>Dată o mulțime de numere și un număr țintă T, răspunde la întrebarea:</p>
<p>Există o submulțime a cărei sumă este exact T ?</p></li>
</ul>
<p>Mai precis, Subset Sum este o problemă Knapsack în care greutatea și valoarea sunt egale.</p>
<p>Acest probleme fac parte din clasa problemelor NP-complete. Ele sunt dintre cele mai dificil de rezolvat (la modul general, algoritmic) deoarece timpul de rulare crește exponențial.</p>
<p><br></p>
<p>Căutând online, găsim diverși algoritmi pentru Knapsack Problem. Lucrarea folosește un astfel de algoritm care este adaptat la problema în cauză.</p>
<p><br></p>
<p>Strategia va fi:</p>
<ul>
<li><p>Dacă numărul pe care vrem să-l obținem epuizează Seria 3 și trebuie să folosească piese din Seria 2, atunci vom folosi algoritmul dinamic pentru a găsi combinația potrivită.</p></li>
<li><p>Trecerea va fi o punte între algoritmul prezentat până acum și cel dinamic. Puntea tratează cazurile particulare care apar la limite.</p></li>
</ul>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># de aici incolo , pentru numere mai mari de aprox 19.7 va fi nevoie sa folosim blocuri din</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Seria 2, serie care are cele mai multe blocuri iar faptul ca elementele ei nu sunt multipli unul fata</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># de celalalt, nu merge sa folosim tot o metoda Greedy optimizata.</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Din acest motiv voi folosi un algoritm dinamic pe care l-am gasit pe internet si l-am adaptat problemei mele.</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Algoritmul in cauza este folosit pentru a rezolva o problema de tip Knapsack.</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Problema pe care o descriu eu aici este similara cu o problema de tip Subset Sum, care</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># este un caz particular al problemei Knapsack.</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> nr<span class="op">&lt;</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="dv">5</span>):</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> comb</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>      <span class="co"># aici o heuristica care regleaza cazurile limita</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>      <span class="co"># de la trecerea dintre Seria 3 si Seria 2</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> <span class="bu">round</span>(nr, <span class="dv">4</span>)<span class="op">&lt;</span><span class="fl">0.25</span>:</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>        k <span class="op">=</span> <span class="bu">round</span>(<span class="fl">.25</span><span class="op">-</span>nr, <span class="dv">5</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>        nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">+</span> k, <span class="dv">5</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>        comb.remove(k)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>      <span class="cf">elif</span> <span class="bu">abs</span>(nr<span class="op">-</span><span class="fl">.3</span>)<span class="op">&lt;</span><span class="dv">10</span><span class="op">**</span>(<span class="op">-</span><span class="dv">5</span>):</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        k <span class="op">=</span> <span class="bu">round</span>(<span class="fl">.35</span><span class="op">-</span>nr, <span class="dv">5</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>        nr <span class="op">=</span> <span class="bu">round</span>(nr<span class="op">+</span>k, <span class="dv">5</span>)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>        comb.remove(k)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    s1 <span class="op">=</span> [<span class="bu">int</span>(<span class="bu">round</span>(x<span class="op">*</span><span class="dv">10000</span>, <span class="dv">5</span>)) <span class="cf">for</span> x <span class="kw">in</span> s1][::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    s2 <span class="op">=</span> [<span class="bu">int</span>(<span class="bu">round</span>(x<span class="op">*</span><span class="dv">10000</span>, <span class="dv">5</span>)) <span class="cf">for</span> x <span class="kw">in</span> s2][::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    s3 <span class="op">=</span> [<span class="bu">int</span>(<span class="bu">round</span>(x<span class="op">*</span><span class="dv">10000</span>, <span class="dv">5</span>)) <span class="cf">for</span> x <span class="kw">in</span> s3][::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> s3<span class="op">+</span>s2<span class="op">+</span>s1</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    nr <span class="op">=</span> <span class="bu">int</span>(<span class="bu">round</span>(nr<span class="op">*</span><span class="dv">10000</span>))</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    comb.extend([x<span class="op">/</span><span class="dv">10000</span> <span class="cf">for</span> x <span class="kw">in</span> printknapSack(nr, s, s, <span class="bu">len</span>(s))])</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> comb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Partea de mai sus reprezintă puntea dintre algoritmul meu și cel dinamic. Algoritmul dinamic este apelat în penultimul rând prin funcția printkanpSack().</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The next part of the code is contributed by Aryan Garg</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Python3 code for Dynamic Programming</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># based solution for 0-1 Knapsack problem</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Prints the items which are put in a</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># knapsack of capacity W</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> printknapSack(W, wt, val, n):</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    K <span class="op">=</span> [[<span class="dv">0</span> <span class="cf">for</span> w <span class="kw">in</span> <span class="bu">range</span>(W <span class="op">+</span> <span class="dv">1</span>)]</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n <span class="op">+</span> <span class="dv">1</span>)]</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Build table K[][] in bottom</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># up manner</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> w <span class="kw">in</span> <span class="bu">range</span>(W <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> i <span class="op">==</span> <span class="dv">0</span> <span class="kw">or</span> w <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>                K[i][w] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>            <span class="cf">elif</span> wt[i <span class="op">-</span> <span class="dv">1</span>] <span class="op">&lt;=</span> w:</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>                K[i][w] <span class="op">=</span> <span class="bu">max</span>(val[i <span class="op">-</span> <span class="dv">1</span>]</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>                  <span class="op">+</span> K[i <span class="op">-</span> <span class="dv">1</span>][w <span class="op">-</span> wt[i <span class="op">-</span> <span class="dv">1</span>]],</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>                               K[i <span class="op">-</span> <span class="dv">1</span>][w])</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>                K[i][w] <span class="op">=</span> K[i <span class="op">-</span> <span class="dv">1</span>][w]</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># stores the result of Knapsack</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    res <span class="op">=</span> K[n][W]</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    w <span class="op">=</span> W</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    lst <span class="op">=</span> []</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n, <span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> res <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>        <span class="co"># either the result comes from the</span></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>        <span class="co"># top (K[i-1][w]) or from (val[i-1]</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>        <span class="co"># + K[i-1] [w-wt[i-1]]) as in Knapsack</span></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>        <span class="co"># table. If it comes from the latter</span></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>        <span class="co"># one/ it means the item is included.</span></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> res <span class="op">==</span> K[i <span class="op">-</span> <span class="dv">1</span>][w]:</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>            <span class="co"># This item is included.</span></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>            <span class="co">#print(wt[i - 1])</span></span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>            lst.append(wt[i<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Since this weight is included</span></span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>            <span class="co"># its value is deducted</span></span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a>            res <span class="op">=</span> res <span class="op">-</span> val[i <span class="op">-</span> <span class="dv">1</span>]</span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a>            w <span class="op">=</span> w <span class="op">-</span> wt[i <span class="op">-</span> <span class="dv">1</span>]</span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> lst</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Partea de mai sus este algoritmul dinamic luat de pe geeksforgeeks<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>.</p>
<p><br></p></li>
</ol></li>
</ol>
</section>
<section id="algoritm" class="level2">
<h2 class="anchored" data-anchor-id="algoritm">3.2 Algoritm</h2>
<p>Algoritmul poate fi consultat și testat aici.</p>
<p><a href="https://colab.research.google.com/drive/1UwWaq-UNZ_lxWgTIHWWyp83AD7eGe1tR?usp=sharing">https://colab.research.google.com/drive/1UwWaqUNZ_lxWgTIHWWyp83AD7eGe1tR#scrollTo=Q9zq9xZAVJCp</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2014.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.15 QR-code către Notebook-ul Colab care conține codul prezentat mai sus, poate fi rulat direct din browser.</figcaption>
</figure>
</div>
<p><br></p>
<p>Am aplicat acest algoritm pe un fișier .csv în care am pus, în ordine crescătoare, toate cele 261536 de măsuri ce pot fi construite folosind setul cu 81 de cale plan paralele.</p>
<p>Folosind acest fișier, am creat o aplicație interactivă ShinyLive prin care oricine poate introduce un număr și, dacă el este valid, va primi combinația optimă. O puteți găsi pe această pagină în tabul <a href="https://vladmarianciuc.github.io/gauge-block-study/gaugefinder.html">GaugeBlock Finder</a>.</p>
<p><a href="https://vladmarianciuc.github.io/gauge-block-study/" class="uri">https://vladmarianciuc.github.io/gauge-block-study/</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2015.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.16 QR-code către aplicația interactivă construită folosind rezultatele acestei lucrări, poate fi deschisă direct în browser.</figcaption>
</figure>
</div>
<p><br></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2016.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.17 Distributia combinatiilor, in functie de marimea pe care vrem sa o construim.</figcaption>
</figure>
</div>
<p><br></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2017.jpg" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig. 18 Evidențierea naturii liniare pe intervale a acestei distribuții.</figcaption>
</figure>
</div>
<p><br></p>
<p>Se observă natură liniară pe intervale a acestei distribuții. Mai precis, exact pe intervalele care coincid cu Seriile de cale pe care le folosim. Pentru fiecare interval putem construi un model de regresie liniară simplă și să unim rezultatele într-o funcție generală de interpolare.</p>
<p>Acest lucru corespunde cu intuiția. Este normal ca distribuția să arate astfel întrucât folosim treptat cale din cele 4 serii până ce epuizăm fiecare serie. Mai mult, pantele interpolărilor pe intervale corespund granulației seriilor.</p>
<p>Vedem o pantă lină pentru seria 4: adică putem obține o plajă largă de numere (pentru că avem calele de dimensiuni mari: 1, 2, 3, 4). O pantă mai abruptă pe intervalul 10-19.5, ce corespunde Seriei 3 și o pantă foarte abruptă după 19.5 – lucru ce se datorează granulației semnificativ mai mici a calelor din Seria 2.</p>
<p><br></p>
</section>
</section>
<section id="incertitudinea-unei-măsurători" class="level1">
<h1>4. Incertitudinea unei măsurători</h1>
<p>Știința care se ocupă cu măsurători se numește metrologie. Ea are un rol semnificativ în domenii medicale, de cercetare, în producție și design. Un aspect cheie în metrologie este stabilirea acurateței unei măsurători, definirea unor grade de precizie și crearea unor metode și standarde internaționale. Faimosul Sistem Internațional a fost unul din acestea iar astăzi avem standardele ISO (dar și altele).<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
<p>Este important să înțelegem că nici o măsură nu este exactă sau precisă. Acest lucru este, defapt, un alt fel de a spune că probabilitatea de a alege un număr rațional este 0 și că probabilitatea de a alege un număr irațional este 1.</p>
<p>De exemplu: Uitându-ne la Fig.18 vedem că avem un creion lângă o linie gradată cu cm și fiecare cm este împărțit în alte 10 gradații (mm). Putem spune rapid că acel creion are cam 4 cm. Putem să mijim mai mult ochii și să spunem că are cam 4.2. Putem fi puțin pedanți și să spunem chiar 4.25! Dar chiar și așa, afirmația noastră tot va conține acel cam. Corect este să spunem 4.25 +/- o toleranță.</p>
<p>Toleranța este o caracteristică a instrumentului cu care este realizată măsurătoarea iar în funcție de precizia la care dorim să lucrăm, ne alegem instrumentele de măsură care au toleranțe acceptabile. De exemplu, dacă realizez un gard de împrejmuire s-ar putea să fie bună o ruletă mare cu diviziuni din cm în cm și care are toleranța de +/- .5 cm. Dar dacă vreau să chertez 2 grinzi din lemn și doresc o îmbinare perfectă, voi avea nevoie de o ruletă mai mică cu diviziuni din mm în mm și cu toleranță mai mică de +/- .5 mm.</p>
<p>De aici vine incertitudinea unei măsurători. Iar legat de incertitudine este conceptul de încredere. Gândindu-ne din nou la creionul din Fig.18, putem spune că are 4.2 cm +/- 0.5 mm. În felul acesta încadrăm incertitudinea în niște limite. Dar putem să spunem că creionul are 4.2 cm +/- 1 mm. Cu cât sunt mai mari limitele în care încadrăm incertitudinea, cu atât este mai mare încrederea noastră că acestea cuprind valoarea „adevărată”. Aș putea, deci, să mă uit la acel creion și să spun că sunt 75% sigur că are 4.2 cm +/- 0.5 mm sau aș putea spune că sunt 90% sigur că are 4.2 cm +/- 1 mm.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2018.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.19 Ce mărime are creionul?</figcaption>
</figure>
</div>
<p><br></p>
<section id="cale-plan-paralele-caracteristici-metrologice" class="level2">
<h2 class="anchored" data-anchor-id="cale-plan-paralele-caracteristici-metrologice">4.1 Cale plan paralele – caracteristici metrologice</h2>
<section id="condiții-standard-de-referință" class="level3">
<h3 class="anchored" data-anchor-id="condiții-standard-de-referință">4.1.1 Condiții standard de referință</h3>
<p>Lungimea unei cale plan paralelă este definită în relație cu următoarele condiții de referință standard:<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
<ul>
<li><p>temperatura = 20 ºC (68 ºF)</p></li>
<li><p>presiune barometrică = 101.325 Pa (1 atmosferă)</p></li>
<li><p>presiunea vaporilor de apă = 1.333 Pa (10 mm de mercur)</p></li>
<li><p>Conținutul de CO2 al aerului = 0.03%</p></li>
</ul>
<p>Dintre aceste condiții doar temperatura are un efect măsurabil asupra lungimii fizice a blocului. Celelalte condiții sunt necesare deoarece măsurarea primară a lungimii blocului de măsurare este o comparație cu lungimea de undă a luminii.</p>
<p><br></p>
</section>
<section id="stratul-de-calare" class="level3">
<h3 class="anchored" data-anchor-id="stratul-de-calare">4.1.2 Stratul de calare</h3>
<p>Capacitatea de calare a calelor este o mărturie privind integritatea stării suprafeței lor.</p>
<p>Dacă niște cale plan paralele nu pot fi calate cu ușurință, atunci ele pot da rezultate neregulate pe care nu te poți baza.</p>
<p>Grosimea stratului de calare dintre 2 cale este de 25 nanometri ~ 0.98 μin<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a>. Iar această dimensiune este incorporată în lungimea calei în sine. Valoarea nominală a unei cale este definită în condițiile de la 4.1.1 prin măsurare interferometrică atunci când blocul este deja calat pe o placă plană de referință. Prin urmare, grosimea stratului de calare este inclusă în valoarea nominală a calei!<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2019a.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.20 Valoarea nominală a unei cale plan paralele include stratul de calare.</figcaption>
</figure>
</div>
<p>Această definiție este foarte utilă, deoarece atunci când calele sunt asamblate în diferite combinații, nu trebuie adăugat niciun factor de corecție suplimentar pentru grosimile straturilor de calare. <br></p>
</section>
<section id="grade-de-toleranță" class="level3">
<h3 class="anchored" data-anchor-id="grade-de-toleranță">4.1.3 Grade de toleranță</h3>
<p>Conform NIST (National Institude of Standards and Technology)<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a>, există 4 grade de toleranță:</p>
<ul>
<li><p>Gradul 0.5</p></li>
<li><p>Gradul 1</p></li>
<li><p>Gradul 2</p></li>
<li><p>Gradul 3</p></li>
</ul>
<p>Calele din gradele 0.5 și 1 au lungimi foarte apropiate de valorile lor nominale. Acestea sunt utilizate de obicei ca referință pentru a calibra alte cale de grade mai mici. Clasele 2 și 3 sunt de calitate inferioară și sunt utilizate în scopuri de măsurare, ateliere mecanice, mașinisti șamd.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2019.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.21 Valoarea nominală a unei cale plan paralele include stratul de calare.</figcaption>
</figure>
</div>
<p><br></p>
<p>Citind acest tabel aflăm despre calele de grad 0.5:</p>
<ul>
<li><p>calele mai mici de 1 inch au lungimea reală în interval de +/- 1 µin față de cea nominală</p></li>
<li><p>cala de 2 inch are lungimea reală în interval de +/-1 µin față de cea nominală, șamd.</p></li>
</ul>
<p><u>De exemplu:</u></p>
<ol type="1">
<li><p>O cală de grad 0.5 care are lungimea nominală de 0.1008 inch are lungimea reală cuprinsă în intervalul: [0.100801, 0.100799]</p></li>
<li><p>Aceeași cală, dar de grad 3, va avea lungimea reală cuprinsă în intervalul: [0.100808, 0.100796]</p></li>
</ol>
<p><br></p>
<p><u>Observație:</u></p>
<ul>
<li>Calele de gradul 0.5 și 1 au toleranță simetrică, pe când cele de grad 2 și 3 au toleranță asimetrică. Acest lucru este datorat destinației lor: cele de grad 0.5 și 1 sunt pentru a fi folosite în laborator (de ex. pentru calibrarea altor cale), pe când cele de grad 2 și 3 sunt folosite în ateliere, linii de producție unde (de obicei) se dorește ca media erorii să fie mai degrabă pozitivă.</li>
</ul>
<p><br></p>
</section>
</section>
<section id="remarcă-privind-numărul-de-cale-calate" class="level2">
<h2 class="anchored" data-anchor-id="remarcă-privind-numărul-de-cale-calate">4.2 Remarcă privind numărul de cale calate</h2>
<p>Considerând aspectele tehnice menționate mai sus, apare întrebarea:</p>
<p>În funcție de gradul de toleranță, câte cale pot cala astfel încât să fiu rezonabil de sigur că valoarea nominală se află într-un interval de încredere satisfăcător?</p>
<p><br></p>
<p><u>De exemplu:</u></p>
<ul>
<li><p>Avem nevoie de să setăm freza unei mașini de găurire la <strong>17.2347</strong> inch față de o placă plană de referință.</p>
<p>Folosind algoritmul prezentat mai sus, vedem că pentru a obține această măsură avem nevoie de <strong>16</strong> cale:</p>
<p><strong>[0.1007, 0.134, 1, 2, 3, 4, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.25]</strong></p>
<p>Avem un set de cale plan paralele de grad 1, unul de grad 2 și unul de grad 3. Vrem ca toleranța combinației pe care o vom folosi să fie mai mică de <strong>+/- 0.00005</strong>. Și vrem să fim 95% siguri că măsura reală se va situa în intervalul de sus.</p>
<p>Ce alegem? Sau cum?</p></li>
</ul>
<section id="modelarea-incertitudinii" class="level3">
<h3 class="anchored" data-anchor-id="modelarea-incertitudinii">4.2.1 Modelarea incertitudinii</h3>
<p>Pentru a putea răspunde la întrebarea de mai sus va trebui să creăm un model.</p>
<p>Incertitudinea unei măsurători poate fi modelată printr-o distribuție normală. Ea poate fi modelată și prin alte distribuții precum distribuția log-normală sau gamma.</p>
<p>Avantajele distribuției normale sunt:</p>
<ol type="1">
<li><p>Este des întâlnită în natură. Sau mai precis, în multe scenarii din lumea reală, datele nu urmează o distribuție normală, iar comportamentul lor matematic poate fi destul de complex. Dar Teorema de Limită Centrală ne permite să tratăm distribuția eșantioanelor ca fiind aproximativ normală, făcând analiza statistică mult mai gestionabilă și fezabilă.</p></li>
<li><p>Este ușor de înțeles, este simetrică, potrivită pentru modelarea unor toleranțe centrate simetric.</p></li>
<li><p>Știm că pentru o deviație standard avem încredere de 67%, pentru două deviații standard avem încredere de 95%, pentru 3 deviații standard: încredere de 99,7%.</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://raw.githubusercontent.com/VladMarianciuc/gauge-block-study/main/img/Fig%20-%2020.png" class="lightbox img-fluid figure-img"></p>
<figcaption class="figure-caption">Fig.22 Populația unei distribuții normale în funcție de abaterea standard</figcaption>
</figure>
</div>
<p><br></p>
<p>Pentru că ne dorim să știm că în 95% din cazuri lungimea reală se va afla în intervalul de toleranță din tabelul de la Fig.19, pentru fiecare cală în parte vom crea o variabilă aleatoare a cărei toleranță să corespundă cu două abateri standard.</p>
<p>Vom considera fiecare cală dintr-o combinație ca pe o variabilă aleatoare i.i.d.</p>
<p>Vom aduna fiecare variabilă i.i.d. și, pentru că toate sunt distribuite după o normală, suma lor va fi tot o distribuție normală. Mai mult, aceasta va reprezenta, defapt, „gradul de toleranță a acelei combinații specifice”.</p>
<p>Ne rămâne să calculăm deviația standard a acestei noi distribuții și să generăm intervalul în care vom ști că, în 95% din cazuri, se află lungimea reală o combinației de cale pe care le vom cala.</p>
<p><br></p>
</section>
<section id="formulare-matematică-algoritm" class="level3">
<h3 class="anchored" data-anchor-id="formulare-matematică-algoritm">4.2.2 Formulare matematică + algoritm</h3>
<p><span class="math display">\[fie\ \mathrm{S}_x⊆\mathcal{S}\ a.i.\ \sum\mathrm{S}_x=x,\ \mathrm{S}_x=\{s_1,s_2,...,s_n\},\ n\in\overline{1,81}\]</span></p>
<p>Vom lua ca exemplu mărimea de mai sus, <strong>17.2347</strong>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>comb <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.1007</span>, <span class="fl">0.134</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="fl">0.95</span>, <span class="fl">0.9</span>, <span class="fl">0.85</span>, <span class="fl">0.8</span>, <span class="fl">0.75</span>, <span class="fl">0.7</span>, <span class="fl">0.65</span>, <span class="fl">0.6</span>, <span class="fl">0.55</span>, <span class="fl">0.25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><br></p>
<p>Definim modele pentru fiecare grad de toleranță.</p>
<p>Gradul 1:</p>
<p><span class="math display">\[\mathrm{G}_1 = \Bigg\{\sum_{i=1}^{n}X_{1,\ s_i}:\ X_{1,\ s_i}\sim\begin{cases}\mathcal{N}(\mu=0,\ \sigma=1\cdot10^{-6}),\ s_i\le1\\\mathcal{N}(\mu=0,\ \sigma=2\cdot10^{-6}),\ s_i=2\\\mathcal{N}(\mu=0,\ \sigma=2.5\cdot10^{-6}),\ s_i=3\\\mathcal{N}(\mu=0,\ \sigma=3\cdot10^{-6}),\ s_i=4\end{cases},\ s_i\in\mathrm{S}_x\Bigg\}\]</span></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq</span>(<span class="fu">length</span>(comb))){</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(comb[i]<span class="sc">&lt;</span><span class="dv">1</span><span class="sc">+</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    g1 <span class="ot">&lt;-</span> g1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="dv">0</span>, <span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  } </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">2</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    g1 <span class="ot">&lt;-</span> g1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="dv">0</span>, <span class="dv">2</span><span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">3</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    g1 <span class="ot">&lt;-</span> g1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="dv">0</span>, (<span class="fl">2.5</span>)<span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">4</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    g1 <span class="ot">&lt;-</span> g1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="dv">0</span>, <span class="dv">3</span><span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><br></p>
<p>Gradul 2:</p>
<p><span class="math display">\[\mathrm{G}_2 = \Bigg\{\sum_{i=1}^{n}X_{2,\ s_i}:\ X_{2,\ s_i}\sim\begin{cases}\mathcal{N}(\mu=1\cdot10^{-6},\ \sigma=1.5\cdot10^{-6}),\ s_i\le1\\\mathcal{N}(\mu=2\cdot10^{-6},\ \sigma=3\cdot10^{-6}),\ s_i=2\\\mathcal{N}(\mu=2.5\cdot10^{-6},\ \sigma=3.75\cdot10^{-6}),\ s_i=3\\\mathcal{N}(\mu=3\cdot10^{-6},\ \sigma=4.5\cdot10^{-6}),\ s_i=4\end{cases},\ s_i\in\mathrm{S}_x\Bigg\}\]</span></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq</span>(<span class="fu">length</span>(comb))){</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(comb[i]<span class="sc">&lt;</span><span class="dv">1</span><span class="sc">+</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    g2 <span class="ot">&lt;-</span> g2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="fl">0.000001</span>, <span class="fl">1.5</span><span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  } </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">2</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    g2 <span class="ot">&lt;-</span> g2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="fl">0.000002</span>, <span class="dv">3</span><span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">3</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    g2 <span class="ot">&lt;-</span> g2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="fl">0.0000025</span>, (<span class="fl">3.75</span>)<span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">4</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    g2 <span class="ot">&lt;-</span> g2 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="fl">0.000003</span>, (<span class="fl">4.5</span>)<span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><br></p>
<p>Gradul 3:</p>
<p><span class="math display">\[\mathrm{G}_3 = \Bigg\{\sum_{i=1}^{n}X_{3,\ s_i}:\ X_{3,\ s_i}\sim\begin{cases}\mathcal{N}(\mu=2\cdot10^{-6},\ \sigma=3\cdot10^{-6}),\ s_i\le1\\\mathcal{N}(\mu=4\cdot10^{-6},\ \sigma=6\cdot10^{-6}),\ s_i=2\\\mathcal{N}(\mu=5\cdot10^{-6},\ \sigma=7.5\cdot10^{-6}),\ s_i=3\\\mathcal{N}(\mu=6\cdot10^{-6},\ \sigma=9\cdot10^{-6}),\ s_i=4\end{cases},\ s_i\in\mathrm{S}_x\Bigg\}\]</span></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="fu">seq</span>(<span class="fu">length</span>(comb))){</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(comb[i]<span class="sc">&lt;</span><span class="dv">1</span><span class="sc">+</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    g3 <span class="ot">&lt;-</span> g3 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="fl">0.000002</span>, <span class="dv">3</span><span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  } </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">2</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    g3 <span class="ot">&lt;-</span> g3 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="fl">0.000004</span>, <span class="dv">6</span><span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">3</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    g3 <span class="ot">&lt;-</span> g3 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="fl">0.000005</span>, (<span class="fl">7.5</span>)<span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">abs</span>(<span class="fu">round</span>(comb[i]<span class="sc">-</span><span class="dv">4</span>))<span class="sc">&lt;</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">5</span>)){</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    g3 <span class="ot">&lt;-</span> g3 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="fl">0.000006</span>, (<span class="dv">9</span>)<span class="sc">*</span><span class="dv">10</span><span class="sc">^</span>(<span class="sc">-</span><span class="dv">6</span>))</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><br></p>
<p>Folosind relația<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a>:</p>
<p><span class="math display">\[X\sim\mathcal{N}(\mu_X,\ \sigma_X^2)\]</span><br>
<span class="math display">\[Y\sim\mathcal{N}(\mu_Y,\ \sigma_Y^2)\]</span><br>
<span class="math display">\[Z=X+Y\]</span><br> <span class="math display">\[atunci\quad Z\sim\mathcal{N}(\mu_X+\mu_Y,\ \sigma_X^2+\sigma_Y^2)\]</span></p>
<p>Rezultă că:</p>
<p><span class="math display">\[G_j\sim\mathcal{N}\Bigg(\mu_{G_j}=\sum_{i=1}^n\mu_{X_{j,\ s_i}},\ \sigma_{G_j}=\sqrt{\sum_{i=1}^n\sigma_{X_{j,\ s_i}}^2}\Bigg),\ j = \overline{1,3}\]</span></p>
<p>Notăm cu:</p>
<p><span class="math inline">\(\overline{x} := lungimea\ reala\ a\ lui\ x\)</span></p>
<p><span class="math inline">\(\Delta:=\overline{x}-x,\ diferenta\ dintre\ lungimea\ reala\ si\ cea\ nominala\)</span></p>
<p><br></p>
<p><strong>Propoziție:</strong></p>
<p><span id="eq-10"><span class="math display">\[\displaylines{Atunci\ \forall\ \mathrm{S}_x⊆\mathcal{S}\ a.i.\ \sum\mathrm{S}_x=x,\ \mathrm{S}_x=\{s_1,s_2,...,s_n\},\ n\in\overline{1,81},\\ \mathbb{P}(\Delta\in[\mu_{G_j}-2\cdot\sigma_{G_j};\ \mu_{G_j}+2\cdot\sigma_{G_j}])\ ≈\ 95\%} \tag{10}\]</span></span></p>
<p>Unde j = {1, 2, 3} reprezintă gradul de toleranță al calelor folosite.</p>
<p><br></p>
<p><u>Observație:</u></p>
<ul>
<li>Folosind <a href="#eq-10">(10)</a> și variind numărul de cale dintr-o combinație putem găsi o formulă pentru intervalele de folosire rezonabilă a calelor cu diferite grade de precizie. Aici prin interval de folosire rezonabilă înțelegem acel interval în care se găsește limita maxim admis a toleranței de care avem nevoie pentru o anumită măsurătoare.</li>
</ul>
<p><br></p>
<p>Revenind la punctul de la care am plecat:</p>
<ol type="1">
<li><p>Vrem să obținem măsura de <strong>17.2347</strong> inch</p></li>
<li><p>Folosind algoritmul de la capitolul <a href="#optimizare-și-algoritm">3</a> obținem o combinație de <strong>16</strong> cale:</p>
<p><strong>[0.1007, 0.134, 1, 2, 3, 4, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55, 0.25]</strong></p></li>
<li><p>Având 3 seturi de cale plan paralele cu 81 de piese, ne întrebăm pe care ar trebui să îl folosim, considerând că vrem o toleranță a combinației mai mică de <strong>+/- 0.00005</strong>.</p></li>
</ol>
<p>Răspunsul este dat de blocul următor de cod care conține partea de afișare și calcul al algoritmului:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(g1, <span class="at">xlab =</span> <span class="st">"Abatere față de valoarea nominală"</span>, <span class="at">main=</span><span class="st">"Distribuția incertitudinii pentru cale de Grad 1"</span>, <span class="at">breaks=</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="RO_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sd_g1 <span class="ot">=</span> <span class="fu">sd</span>(g1)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media combinației folosind g1 este 0 iar deviația standard este "</span>, <span class="fu">round</span>(sd_g1, <span class="at">digits=</span><span class="dv">7</span>),<span class="st">".</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Media combinației folosind g1 este 0 iar deviația standard este  0.0000057 .</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Combinația cu calele g1 oferă cu 95% încredere toleranța ["</span>,<span class="fu">round</span>(<span class="sc">-</span><span class="dv">2</span><span class="sc">*</span>sd_g1, <span class="at">digits=</span><span class="dv">6</span>), <span class="st">", "</span>, <span class="fu">round</span>(<span class="dv">2</span><span class="sc">*</span>sd_g1, <span class="at">digits=</span><span class="dv">6</span>),<span class="st">"]</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Combinația cu calele g1 oferă cu 95% încredere toleranța [ -0.000011 ,  0.000011 ]</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(g2, <span class="at">xlab =</span> <span class="st">"Abatere față de valoarea nominală"</span>, <span class="at">main=</span><span class="st">"Distribuția incertitudinii pentru cale de Grad 2"</span>,  <span class="at">breaks=</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="RO_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sd_g2 <span class="ot">=</span> <span class="fu">sd</span>(g2)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mean_g2 <span class="ot">=</span> <span class="fu">mean</span>(g2)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media combinației folosind g2 este "</span>,<span class="fu">round</span>(mean_g2, <span class="at">digits=</span><span class="dv">7</span>), <span class="st">" iar deviația standard este "</span>, <span class="fu">round</span>(sd_g2, <span class="at">digits=</span><span class="dv">7</span>),<span class="st">".</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Media combinației folosind g2 este  0.0000205  iar deviația standard este  0.0000085 .</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Combinația cu calele g2 oferă cu 95% încredere toleranța ["</span>,<span class="fu">round</span>(mean_g2<span class="dv">-2</span><span class="sc">*</span>sd_g2, <span class="at">digits=</span><span class="dv">6</span>), <span class="st">", "</span>, <span class="fu">round</span>(mean_g2<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>sd_g2, <span class="at">digits=</span><span class="dv">6</span>), <span class="st">"]</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Combinația cu calele g2 oferă cu 95% încredere toleranța [ 0.000003 ,  0.000038 ]</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(g3, <span class="at">xlab =</span> <span class="st">"Abatere față de valoarea nominală"</span>, <span class="at">main=</span><span class="st">"Distribuția incertitudinii pentru cale de Grad 3"</span>, <span class="at">breaks=</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="RO_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="672"></p>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>sd_g3 <span class="ot">=</span> <span class="fu">sd</span>(g3)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>mean_g3 <span class="ot">=</span> <span class="fu">mean</span>(g3)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media combinației folosind g3 este "</span>,<span class="fu">round</span>(mean_g3, <span class="at">digits=</span><span class="dv">7</span>), <span class="st">" iar deviația standard este "</span>, <span class="fu">round</span>(sd_g3, <span class="at">digits=</span><span class="dv">7</span>),<span class="st">".</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Media combinației folosind g3 este  0.000041  iar deviația standard este  0.000017 .</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Combinația cu calele g3 oferă cu 95% încredere toleranța ["</span>,<span class="fu">round</span>(mean_g3<span class="dv">-2</span><span class="sc">*</span>sd_g3, <span class="at">digits=</span><span class="dv">6</span>), <span class="st">", "</span>, <span class="fu">round</span>(mean_g3<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span>sd_g3, <span class="at">digits=</span><span class="dv">6</span>), <span class="st">"]</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Combinația cu calele g3 oferă cu 95% încredere toleranța [ 0.000007 ,  0.000075 ]</code></pre>
</div>
</div>
<p>Prin urmare, putem folosi calele de grad 1 sau 2. Dacă am folosi calele de grad 1 ar fi cam multă precizie pentru ce avem nevoie, deci le putem folosi pe cele de grad 2, care ne oferă precizia de care avem nevoie!</p>
<p><br></p>
<p><u>Observație:</u> Acest algoritm poate fi aplicat pe setul de date generat cu algoritmul de la capitolul <a href="#optimizare-și-algoritm">3</a> pentru a arăta vizual intervalele de folosire rezonabilă amintite mai sus.</p>
<p><br> Codul de la capitolul <strong>3</strong> a fost scris în limbajul Python, într-un notebook .ipynb Colab.</p>
<p>Codul de la capitolul <strong>4</strong> a fost scris în limbajul R, în I.D.E.-ul RStudio, format Quarto.</p>
<p><br></p>
<p><br></p>
</section>
</section>
</section>
<section id="mulțumesc" class="level1">
<h1>5. Mulțumesc:</h1>
<ul>
<li><p>Prietenului Andrei Negoiță:</p>
<ul>
<li><p>cu care am făcut un semnificativ ping-pong de idei prin care s-a conturat demonstrația problemei de numărare.</p></li>
<li><p>și care a rulat timp de 8 ore (folosind multi-thread) algoritmul de la cap.3) pe cele 261 536 de valori pentru a genera fișierul .csv cu combinațiile fiecărei măsuri.</p></li>
</ul></li>
<li><p>Prietenului Alec Avram, care m-a ajutat cu un proofreading al draftului lucrării în care mi-a semnalat câteva greșeli și mi-a dat recomandări pentru exprimare.</p></li>
<li><p>Iubitei mele, Gabriela Doloiu, pentru suportul emoțional pe care mi l-a acordat în această perioadă foarte, foarte aglomerată.</p></li>
<li><p>Domnilor Cătălin Coman, Fasie Ion-Alexandru și Mihai Iordache care au răspuns cererii mele de pe grupul public de facebook Scule și unelte de calitate, vechi și noi, și alte chestii interesante și mi-au împrumutat instrumente metrologice și seturi de cale plan paralele pentru a le folosi în timpul prezentării lucării.</p></li>
<li><p>Dumneavoastră, pentru timpul acordat lecturii acestei lucrări.</p></li>
</ul>
<p><br></p>
</section>
<section id="bibliografie" class="level1">
<h1>6. Bibliografie</h1>
<ol type="1">
<li><p>Moore, W. R. (1970). <em>Foundations of mechanical accuracy</em> (1st ed., 3rd Print). <a href="https://pearlhifi.com/06_Lit_Archive/15_Mfrs_Publications/Moore_Tools/Foundations_of_Mechanical_Accuracy.pdf" class="uri">https://pearlhifi.com/06_Lit_Archive/15_Mfrs_Publications/Moore_Tools/Foundations_of_Mechanical_Accuracy.pdf</a></p></li>
<li><p>Francis, W. (2017, Noiembrie 22). <em>Origins of precision</em>. Machine Thinking. <a href="https://www.youtube.com/watch?v=gNRnrn5DE58" class="uri">https://www.youtube.com/watch?v=gNRnrn5DE58</a> (ref. 1, 8)</p></li>
<li><p>Doiron, T. and Beers, J. (1995), <em>The Gage Block Handbook</em>, Monograph (NIST MN), National Institute of Standards and Technology, Gaithersburg, MD, [online]. <a href="https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735" class="uri">https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735</a> (ref. 2, 6, 14)</p></li>
<li><p>Webber, S. (2003, November 21). <em>Wringing Gage Blocks.</em> Starret-Webber. <a href="http://www.starrett-webber.com/gb46.html" class="uri">http://www.starrett-webber.com/gb46.html</a> (ref. 3, 16, 17, 18)</p></li>
<li><p>Muelaner, J. (2017a, November 1). <em>Key principles in metrology and Measurement Systems Analysis</em> <a href="https://www.muelaner.com/metrology/" class="uri">https://www.muelaner.com/metrology/</a> (ref. 4, 13)</p></li>
<li><p>A&amp;E Television Networks. (n.d.). <em>Interchangeable parts</em>. History.com. <a href="https://www.history.com/topics/inventions/interchangeable-parts" class="uri">https://www.history.com/topics/inventions/interchangeable-parts</a> (ref. 5)</p></li>
<li><p><em>The history of gauge blocks.</em> (n.d.) <a href="https://www.mitutoyo.com/webfoo/wp-content/uploads/E12016-History-of-The-Gage-Block.pdf" class="uri">https://www.mitutoyo.com/webfoo/wp-content/uploads/E12016-History-of-The-Gage-Block.pdf</a>(ref. 7)</p></li>
<li><p>Wikimedia Foundation. (n.d.). Wikipedia. <a href="https://en.wikipedia.org/" class="uri">https://en.wikipedia.org/</a> (ref. 9, 10, 12, 15, 19)</p></li>
<li><p>Garg, A. (2022, June 23). <em>Printing items in 0/1 Knapsack</em>. GeeksforGeeks. <a href="https://www.geeksforgeeks.org/printing-items-01-knapsack/" class="uri">https://www.geeksforgeeks.org/printing-items-01-knapsack/</a> (ref. 11)</p></li>
</ol>
<p><br></p>
</section>
<section id="imagini" class="level1">
<h1>7. Imagini</h1>
<ol type="1">
<li><p>Fig.1 Foaia de prezentare al unui set cu 81 de cale plan paralele din 1944. Francis, W. (2017, Noiembrie 22). <em>Origins of precision</em>. Machine Thinking, min. 16:58 <a href="https://www.youtube.com/watch?v=gNRnrn5DE58" class="uri">https://www.youtube.com/watch?v=gNRnrn5DE58</a></p></li>
<li><p>Fig.2 Afirmațiile de la care a pornit lucrarea (zoom Fig.1, ibidem)</p></li>
<li><p>Fig.3 Cale plan paralele (sistem metric) Stenström, E. (2021, Martie 23). <em>Gauge blocks – the foundation to all modern industrial production.</em> Elastocon. <a href="https://www.elastocon.com/learn-more/about-calibration/gauge-blocksthe-foundation-to-all-modern-industrial-production" class="uri">https://www.elastocon.com/learn-more/about-calibration/gauge-blocksthe-foundation-to-all-modern-industrial-production</a></p></li>
<li><p>Fig.4 Procedeul de calare a 2 cale (ibidem referința 3)</p></li>
<li><p>Fig.5 Mai multe cale sunt calate pentru a obține o dimensiune. Se observă cum ele rămân lipite sub acțiunea gravitației. Clarence Leon Goodrich &amp; Frank Arthur Stanley (1907) <em>Accurate Tool Work,</em> McGraw-Hill, New York, p.185, fig.196</p></li>
<li><p>Fig.6 Setul de 81 de piese realizat de C.E. Johansson pentru fabricile Ford pe care Ford însuși l-a făcut cadou bunului său prieten, Thomas Edison. Acum acest set se află la Muzeul Preciziei din Windsor, Vermont, Statele Unite ale Americii. <a href="https://americanprecision.org/wp-content/uploads/2020/06/IMG_1696.jpeg" class="uri">https://americanprecision.org/wp-content/uploads/2020/06/IMG_1696.jpeg</a></p></li>
<li><p>Descriere schematică a intuiției. Imagine proprie.</p></li>
<li><p>Fig.8 Toate măsurătorile au un grad de incertitudine iar cu cât marjele alese sunt mai mari, cu atât crește încrederea. Muelaner, J. (2017, November 1). <em>Key principles in metrology and Measurement Systems Analysis (MSA)</em>. <a href="https://www.muelaner.com/metrology/#uncertainty" class="uri">https://www.muelaner.com/metrology/#uncertainty</a></p></li>
<li><p>Fig.9 C.E. Johansson ținând în mână un „baton” de cale <a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjdc0vJRCaT_eIscJyFuiR6VYli7lShAZo8bx5EJSdqqUxnSGiFXAoEanO3fPC1ab2_HbqPcgzSwyz6JXDqcQ4uBoTNg3ZTUSjywV8MsCmMOS3JOkimLh_vveardZHtOu78BtkzfUp6-I/s1600/CE+Johansson.jpg" class="uri">https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjdc0vJRCaT_eIscJyFuiR6VYli7lShAZo8bx5EJSdqqUxnSGiFXAoEanO3fPC1ab2_HbqPcgzSwyz6JXDqcQ4uBoTNg3ZTUSjywV8MsCmMOS3JOkimLh_vveardZHtOu78BtkzfUp6-I/s1600/CE+Johansson.jpg</a></p></li>
<li><p>Fig.10 Schema structurii simetrice a intervalului studiat. Imagine proprie.</p></li>
<li><p>Fig.11 Descriere schematică a intuiției ajustate. Imagine proprie.</p></li>
<li><p>Fig.12 Evoluția intuiție pe parcursul realizării acestei lucrări. Imagine proprie.</p></li>
<li><p>Fig.13 Când construim o măsura X, rămâne măsura Total – X. Imagine proprie</p></li>
<li><p>Fig.14 Vizualizare schematică a modului de căutare a combinației optime. Imagine proprie.</p></li>
<li><p>Fig.15 QR-code către Notebook-ul Colab cu algoritmul din cap. 3).</p></li>
<li><p>Fig.16 QR-code către aplicația interactivă Shinylive, poate fi deschisă direct în browser</p></li>
<li><p>Fig.17 Distributia combinațiilor, în functie de mărimea pe care vrem sa o construim. Img. proprie.</p></li>
<li><p>Fig. 18 Evidențierea naturii liniare pe intervale a acestei distribuții. Imagine proprie.</p></li>
<li><p>Fig.19 Ce mărime are creionul? <a href="https://media.baamboozle.com/uploads/images/47624/1588733513_88858" class="uri">https://media.baamboozle.com/uploads/images/47624/1588733513_88858</a></p></li>
<li><p>Fig.20 Valoarea nominală a unei cale plan paralele include stratul de calare. (Ibidem (ref. 16))</p></li>
<li><p>Fig.21 Grade de toleranță pentru cale sistem imperial (exprimat in µin = 10-6 in). (ref. 18)</p></li>
<li><p>Fig.22 Populația unei distribuții normale în funcție de abaterea standard <a href="https://sphweb.bumc.bu.edu/otlt/MPH-Modules/PH717-QuantCore/PH717-Module6-RandomError/Normal%20Distribution%20deviations.png" class="uri">https://sphweb.bumc.bu.edu/otlt/MPH-Modules/PH717-QuantCore/PH717-Module6-RandomError/Normal%20Distribution%20deviations.png</a></p></li>
</ol>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Francis, W. (2017, Noiembrie 22). <em>Origins of precision</em>. Machine Thinking.<br> <a href="https://www.youtube.com/watch?v=gNRnrn5DE58" class="uri">https://www.youtube.com/watch?v=gNRnrn5DE58</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Doiron, T. and Beers, J. (1995), <em>The Gage Block Handbook</em>, Monograph (NIST MN), National Institute of Standards and Technology, Gaithersburg, MD, [online], p.10<br> <a href="https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735" class="uri">https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Webber, S. (2003, November 21). <em>Wringing Gage Blocks. Starret-Webber</em>.<br> <a href="http://www.starrett-webber.com/gb46.html" class="uri">http://www.starrett-webber.com/gb46.html</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Muelaner, J. (2017a, November 1). <em>Key principles in metrology and Measurement Systems Analysis (MSA).</em><br> <a href="https://www.muelaner.com/metrology/" class="uri">https://www.muelaner.com/metrology/</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>A&amp;E Television Networks. (n.d.). <em>Interchangeable parts</em>. History.com.<br> <a href="https://www.history.com/topics/inventions/interchangeable-parts" class="uri">https://www.history.com/topics/inventions/interchangeable-parts</a><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Doiron, T. and Beers, J. (1995), <em>The Gage Block Handbook</em>, Monograph (NIST MN), National Institute of Standards and Technology, Gaithersburg, MD, [online], p.8<br> <a href="https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735" class="uri">https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735</a><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><em>The history of gauge blocks.</em> (n.d.), p.8.<br><a href="https://www.mitutoyo.com/webfoo/wp-content/uploads/E12016-Historyof-The-Gage-Block.pdf" class="uri">https://www.mitutoyo.com/webfoo/wp-content/uploads/E12016-Historyof-The-Gage-Block.pdf</a><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Francis, W. (2017, Noiembrie 22). <em>Origins of precision.</em> Machine Thinking, min. 29:55<br> <a href="https://youtu.be/gNRnrn5DE58?si=bz9xrtXgltSV4QQR&amp;t=1795" class="uri">https://youtu.be/gNRnrn5DE58?si=bz9xrtXgltSV4QQR&amp;t=1795</a><a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Wikimedia Foundation. (2024a, May 13). <em>Knapsack problem</em>. Wikipedia. <a href="https://en.wikipedia.org/wiki/Knapsack_problem" class="uri">https://en.wikipedia.org/wiki/Knapsack_problem</a><a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Wikimedia Foundation. (2024, June 9). <em>Subset sum problem.</em> Wikipedia. <a href="https://en.wikipedia.org/wiki/Subset_sum_problem" class="uri">https://en.wikipedia.org/wiki/Subset_sum_problem</a><a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Garg, A. (2022, June 23). <em>Printing items in 0/1 Knapsack</em>. GeeksforGeeks. <a href="https://www.geeksforgeeks.org/printing-items-01-knapsack/" class="uri">https://www.geeksforgeeks.org/printing-items-01-knapsack/</a><a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Wikimedia Foundation. (2024b, June 1). <em>Metrology</em>. Wikipedia. <a href="https://en.wikipedia.org/wiki/Metrology" class="uri">https://en.wikipedia.org/wiki/Metrology</a><a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Muelaner, J. (2017a, November 1). <em>Key principles in metrology and Measurement Systems Analysis (MSA).</em> <a href="https://www.muelaner.com/metrology/#uncertainty" class="uri">https://www.muelaner.com/metrology/#uncertainty</a><a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Doiron, T. and Beers, J. (1995), <em>The Gage Block Handbook</em>, Monograph (NIST MN), National Institute of Standards and Technology, Gaithersburg, MD, [online], p.10 <a href="https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735" class="uri">https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735</a><a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Wikimedia Foundation. <em>Gauge block.</em> Wikipedia. <a href="https://en.wikipedia.org/wiki/Gauge_block">http://www.starrett-webber.com/gb46.htm</a><a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>Webber, S. (2003, November 21). <em>Wringing Gage Blocks</em>. Starret-Webber. <a href="http://www.starrett-webber.com/gb46.html" class="uri">http://www.starrett-webber.com/gb46.html</a><a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Doiron, T. and Beers, J. (1995), <em>The Gage Block Handbook</em>, Monograph (NIST MN), National Institute of Standards and Technology, Gaithersburg, MD, [online], p.13 <a href="https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735" class="uri">https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=820735</a><a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>Wikimedia Foundation. (2023, August 12). <em>Sum of normally distributed random variables</em>. Wikipedia. <a href="https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables" class="uri">https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables</a><a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>